### ISSUE TITLE
Have scheduled return a disposer function

### ISSUE THREAD

**Issue by snnsnn** [solidjs-community/solid-primitives#135]
Wouldn't it be better if a scheduled returns a disposer function. This way they mirror the built-in timers like `setTimeout` and you can't clear unless you set one.

```typescript
const trigger = debounce((message: string) => console.log(message), 250);
const clear = trigger("Hello!");
clear();
```

**Comment by thetarnav** [comment]
Well it looks clean, sure. But there is a problem. The clean function isn't tired to a specific trigger, it's "global" - always clearing the current timer.
Also you cannot assign the clear function to a variable before triggering the callback in the process.
The current API may look worse, but I think it's more practical.

**Comment by snnsnn** [comment]
You are right. Current implementation is way more flexible. Thanks.
