### ISSUE TITLE
Color scheme primitive

### ISSUE THREAD

**Issue by Guergeiro** [solidjs-community/solid-primitives#155]
Nowadays [browsers support](https://caniuse.com/matchmedia) checking for the current theme of the user.
React way of doing:
```ts
// React
const useThemeDetector = () => {
    const getCurrentTheme = () => window.matchMedia("(prefers-color-scheme: dark)").matches;
    const [isDarkTheme, setIsDarkTheme] = useState(getCurrentTheme());  
    const mqListener = (e => {
        setIsDarkTheme(e.matches);
    });
    
    useEffect(() => {
      const darkThemeMq = window.matchMedia("(prefers-color-scheme: dark)");
      darkThemeMq.addListener(mqListener);
      return () => darkThemeMq.removeListener(mqListener);
    }, []);
    return isDarkTheme;
}
```

**Comment by thetarnav** [comment]
Yeah, that's a neat idea. We have a `media` package that this could fit in nicely.
I think that currently, you could achieve that quite easily with [`createMediaQuery` primitive](https://github.com/solidjs-community/solid-primitives/tree/main/packages/media#createMediaQuery).
It would require remembering the media query to write.
```ts
import { createMediaQuery } from "@solid-primitives/media";

const prefersDark = createMediaQuery("(prefers-color-scheme: dark)");
console.log(prefersDark());
```

So a `usePrefersDark` primitive could be added with such API:
```ts
import { usePrefersDark } from "@solid-primitives/media";

const prefersDark = usePrefersDark();
console.log(prefersDark());
```
It could use a [shared root](https://github.com/solidjs-community/solid-primitives/tree/main/packages/rootless#createSharedRoot) to not recreate the signal and event-listener each time.
