### ISSUE TITLE
@solid-primitives/event-bus size is way bigger than similiar pkg

### ISSUE THREAD

**Issue by MrFoxPro** [solidjs-community/solid-primitives#170]
@solid-primitives/event-bus package is ~10 times bigger than [nanoevents](https://github.com/ai/nanoevents):

https://bundlephobia.com/package/@solid-primitives/event-bus@0.1.0  1.4 kB 
https://bundlephobia.com/package/nanoevents@7.0.1 274 B 
Feel free to move to discussions if needed.

**Comment by thetarnav** [comment]
That is the size of a full package. Without any tree shaking.
I tried playing with bundle.js.org and `createEmitter` from @solid-primitives/event-bus is `315B`, while the `createNanoEvents` from nanoevents is `182B`.
But that's still twice as much for roughly the same functionality. So thank you for the issue, I'll be probably coming around to event-bus at some point to fix it & improve the API a bit.
