### ISSUE TITLE
Using `@solid-primitives/stream` along with `new MediaStream()` causing chrome & chromium to load forever

### ISSUE THREAD

**Issue by mohanavel15** [solidjs-community/solid-primitives#182]
This bug only affects Chrome & Chromium

Steps to reproduce the bug :
```
npx degit solidjs/templates/ts bug
cd bug
npm i @solid-primitives/stream
npm start
```
App.tsx :
```tsx
import type { Component } from 'solid-js';

declare module "solid-js" {
  namespace JSX {
    interface ExplicitProperties {
      srcObject?: MediaStream
    }
  }
}

const App: Component = () => {
  let Stream = new MediaStream()
  return (
    <div>
      <video class="video" prop:srcObject={Stream} autoplay playsinline></video>
    </div>
  );
};
```
Chromium Version 104.0.5112.79 (Official Build) (64-bit)

just keeping the package installed causing this bug when using `new MediaStream()`
(I'm using `new MediaStream()` for remote streams and `@solid-primitives/stream` for local streams)

This bug also blocks some functionality. not sure what are things but for me it blocks `createStream`

**Comment by atk** [comment]
I have reproduced the same behavior without even installing @solid-primitives/stream (or even without solid), thus I must conclude that this is indeed an issue of Chromium (if not intended behavior) and not an issue with our primitive:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>MediaStream bug test</title>
  </head>
  <body>
    <video autoplay playsinline></video>
    <script>document.querySelector('video').srcObject = new MediaStream()</script>
  </body>
</html>
```

On the other hand, this might work as intended, as the browser tries to load media stream tracks into the video tag, which are never arriving. However, if you refrain from setting srcObject, your page will not expose the described reaction. Thus, the correct usage would be to only set srcObject in the video tag if you have a media stream with tracks inside.
