### ISSUE TITLE
add `createEventDispatcher` primitive

### ISSUE THREAD

**Issue by AyloSrd** [solidjs-community/solid-primitives#186]
A primitive that is the equivalent of [Svelte's `createEventDispatcher` ](https://svelte.dev/docs#run-time-svelte-createeventdispatcher) for Solid, enabling components to dispatch custom events. 

#### Use
`createEventDispatcher` would take the component `props` as argument, and return an event dispatcher function. 
```jsx
const dispatch = createEventDispatcher(props)
```
A component can emit events by creating an event dispatcher and calling it. 
The event dispatcher takes three arguments, the event name (mandatory), the optional payload, and optional dispatcher options.
```jsx
<button onClick={() => dispatch('answer', 42}>Give Answer</button>
```
The parent component would listen to the event as it would listen to any other event on a DOM element, by passing a `on + capitalized name of the event` prop containing the event handler. The payload will be carried in `CustomEvent.detail`
```jsx
<ChildComponent onAnswer={evt => console.log(evt.detail)} /> // will log 42
```
The third parameter is an object that one property, `cancelable`, which determines whether the created custom event is cancelable, and defaults to `{ cancelable: false }`. To parallel [DOM's `dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent), `dispatch` will return `false`, if the custom event is cancelable and `preventDefault()` has been called, `true` in all the other cases (even if there is no event handler associated to the event).

#### TypeScript
The developers should have access to the same suggestions and error signalling as if they were directly accessing the event handlers from the props.
`dispatch` should suggest all the available events, suggest the payload type once the event is chosen, and consider whether a payload is optional or not (and thus signal the error if a mandatory payload is not passed).
Some exemples  :
```tsx
interface Props {
  onStringEvent: (evt: CustomEvent<string>) => void,
  onNumberEvent: (evt: CustomEvent<number>) => void,
  onMandatoryPayload: (evt: CustomEvent<number>) => void,
  onOptionalPayload: (evt?: CustomEvent<string>) => void,
}

dispatch() // will suggest ("stringEvent", "numberEvent", "mandatoryPayload", "optionalPayload")
dispatch('stringEvent', ) // will suggest "(eventName: "changeStep", payload: string, dispatcherOptions?: DispatcherOptions | undefined) => boolean"
dispatch('numberEvent', 'forty-two') // will throw "Error: Argument of type 'string' is not assignable to parameter of type 'number'."
dispatch('mandatoryPayload') // will throw: "Error: Expected 2-3 arguments, but got 1."
dispatch('optionalPayload') // will not complain, but suggest "(eventName: "optionalPayload", payload?: number | undefined, ...
```

I have created a draft [npm package that does it](https://www.npmjs.com/package/solid-create-event-dispatcher), to test if it was possible, and here an mock app that uses it, to see how it works : 

- [SolidJS Playground](https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi8AynAgATOI14BfXgDNGtGLwA6YAHQB6MiPGNVAbmUQOXHv14AxOHFHS5Cpas2zrog0ZPc+Axjol35RV4AcjoAGzRRAFoAKzINAHc4ACNgj04vc2ZfKFw4QTQAc2gwrF5suFy4AFVjAEd6OABJWxlApVDaCOi4tOMMs2DNVAw1ZjIyPqNZeghmXDRaCF4AQUJCAAoASn4jXnKlsj5gXEYiwokLWmZ6MjLtXAAVM8KLxiubsgBdXgBecpyeQKxSgYQAPMlaF1KhAAHwbWSg7RbPYHCBHXjALhHAAyaCO9zguAACrQjmQ8Ucfv8KlVgSUwaj9itGIwoPgwQJmEs8hBcIheEczhBCmVIgKhRhCtJYaj4cAviiIKjuei+AALKBiMJwADCOq1Vhsf142z+sN2y32gqJpPJlNwGwVSv2UiMKsOGq1oh1wjEJo2cAAbvzeLrbrhFABRIMiXBgyUi2E7X4WkBMtEY1W8vj-YO4NTiXDoMIZ1UYyIm2l5WpoBrNUTbDMPO3kB1OtSd7G4dtbMpcnlxsWtRWot3Kq3lr3auAAJTgMFosdbAfzAvDR2jsb5CdOUuT5st1szfEreZDhaJJebtrJbfxju7vbUsjQYTyjA2GxgZEKKYtP6FGolYAIS-P8kRbC60julavi4EwywbBmYKiGgQblGEUATL8qhrIQqiylax5gkabjEcevBLPqMJkb8ICajONGGq446UdaSzzouy53vRjE+nOC5LnArZsexvDdhSD70U+D7bGJx4aER7Fgn6ugqBRx5LB8tw2PRZqpjaTwvG8OlkAiSJwFsCmUUsal8d6vo6DIGbHnuryXNctz0e5pleeZ1mubwSkoRoaFBspvBKuORi+GIEhfv+vBgvhwWwmUohefAfJqBcuBRjq2W4AAQvgLTIWAUDrKoWwgUqYBSFg4DQPASAoOgmA4AQxBteMZDUHQTCsG1AACnhmEwYQVequC4IQZCIBoGiyDyZC5VChQGoQ+JjIoGh9QATAA-IiMBvvgvzVMkswIQA1AAskstCIGgxalAkhQzSNAAMWAACzfd9+i-QA7ID+gAIz-YDABkaFkIQWEXWQCRVTVhh6MqmMAFRYMoOOIIgyRwCtvh4wTiBQLIH67Jj+yQhQURkGgABeUoCpCjC6FEDMY6iK18lEp3nQKqhXTd9C8I9EC0KoZSLjLCNQKwfMQG6mP40YGjY384HgUI2RdGEyRQJIuqCIIut67w2MaJrEDa5YaC+CtFA23bOO06iZCG2Exum1ECSRLg6oClA9CRqr+w+wofsm4wUTcmE3ASoQwqvL4IgAMSyLnee56r6vupjju6uqDhwGUUaiBcZTekIVOm2g7v29jhOBykADWr1M77-uSOmdO8EHoghwKEPfYQFCF-brft0kyTd7gvex-3USnMrnde1aJvMJ3hQKLMogChv6KEKbcYzxrFMd4vPcx0b8fr+q9AwMk2-05vB8MGIiddCngo05SgPtYCAUdeCc25myNCtxx6T2nvbem3BdAChlhAOAV9i5GGurNJYH8IHIIkKgpYGDEEQK-ofX+ScAGnyVnFXA4CbiMDoIwAUXAMAfkwVjbBtBRD4HwagRghQMACiBmQ8+og0IilEVw+2ahUqD1ROqOARQZpwO+kGdU4CR5j14BPDRCRwGoEZso1RoZ9EAFIjFQEZjo0OejAZWLIfDRG7IBSyB1AgoeHi4CMzQr4eYiwIACiTq-MBZDd770odEahrDAHpxASIWRmNlFQHUooq0pjPrmMBlPcBLikbuM8eA0ERQIBRFeguBachPFRB0OAmIEY0CyHwH-PkcYim+LqWIcBEipGFFEbwA68ChkjLEZjIu3CICpPUjgyMywMn7FiQKLOABmdZvS0n9J5rQXBMABQAFY8kRMIQnSEeyJRdErGs9ZQzjkTNnpjEYCyyE+MZt-BI498n4lcfgTpXj+a1P8XAQJSwQldDCSUiIxQKl5B-CEuMEhtHB3sZY8BwlGAeNoJ83g4dI4RIoT-Y+vAs5wG+mSsl4DIESHXrQQgUQdTUyiNAtAsDeAHPgVS05tL6UvBmsytJrLqkcvuUYSZ9tnm4p4GgZgOp8F2PHiKgFVpBHCOCQ4qevBxmompQnFlbKJ6ip3oSo+f9k5xIRgkzO4Sh7LJJes1ZmzJHsw1cq8VTyOpSoWLKuAvBwpqF8NxOAURuzypReopxQ8CluJqb4hpTSWltJzP87pohklGElabb1cr-WBuEiGu8ECI7zPwX0l12qVWmzVTI+27rphQhpos8he9v5HxWRS8lFb9hlukbwVZYzvkI0KbwA+kRelYVYEmjp5REWMHTRAFauz-AYEIBHfBuriHoPAVktRfbOWvNqR8r5JyuY0v1dUiGRzlXdq2eW0ZRq60Lobf4OZeCm2RNbVQ-+FqgEikSTa1ECreAAyNfsHdoYQPXoIaevVgq2XDNA7wVVGAGUkxyYhphLC2G0A4Ui2tjz61LskKTJQTagP6KDIYshxjA7hvZbkqDPaBlavvW7b69HEPRr+bGqDpSYWVPhTO9pc78OYwak1SAsA2DaHiowag3U2DkCoDgQaLA2DjW8ACSoeQYxxgACI-NyMwZRkg2gOBCOESIidATBuDHGKILijMmbSJjDTWQbNRlziC3AZRqz5DKaCMoSxHo3QCOZzo3RYiTAI3yIgvriQKHmiaJt2l-I2AFAZC0QYcOiHJqiOyOgMtrjDBGLccZdzpwPIZbLkQ8tWl8p5T4HMoQGggHVx9vjTB8CnEIPwkh-gbDTnS6pCXhtJSbT1rEd5dSDj5ISEk03Zu4GpFpukAXwSJkKPCVQNUyE6lPBAVduB5yyAFEfEmGBjQAB9eAAAlHj3RxE0Q7EcCoLkvmQnrjncDGarB57cuADNKx+yZwbiWyAomvh6NUch-LPaOwGcbZD9grojido6L5-JNiHo+pZnpeD8R1PDtdA24ACmJ-lAHSOh7R1vEcGb7S+RfjgGoYsQiiS4rIHdh7T2Xv5UKnGLYGOgygkaJDscMW8cw8J-kegyQzq5lNMVwQcuFe6b5NTjM+Y1Bpzs3yPTJNw7vmxxmZppoQLdgZzmbYagdQihDjsJtx54KIWRzBGnfrDMg4qjJtw2AJKLcZ46KCbuWyB+tztsA4urS46ohAELTPMv4P2CtT4FOTcx+j59jzXn5iJUPE760ZuwfDdZyZRrtwdjJ8oqn246fo-iU98D4zGxgi1+0KIYIDfKKTNdFnoeLvGBITd2CRdH5ZQe-2KP7gSg7Kq9eg5GcKv5evSkBPoKU-Ue4Dd+xJYFPF8CQp73xvvAXb0S3yd4-jeFO4TwL47fYAd+URF2ERoMlw9xnkk--YIVJ-WghMWngjfqoGQPPg-uvppJRAmOfMsLHHALfhwIUKoFKmgFAAylAMTGELfgoHvESIRN-pRIALwbgAAXsEFT5aAwEQGN5ggaCvpwhP40EkZUH-7LTPqMDMHR6TLibNRSZtQuA2DyZxZtRKYDQMBqZtRuYCArhmZBBOAaDdjuCuYDCaZ+bq6A5e7Gb+AyGOA0BXIxI2Z1IA4OYaEmaKHpBdbubaZwCeYuDzBlBXCMBlCCDqjYphayG6GRZxBmFTIKa8CjZJb-ApYQDMQQBkQZZJQ1ZppkKcRCQ8RHBFYhjrilYwBqEVb7gRE5a9J3hSTxGrCsjsichojJqCh7gij6C8DiglHpwyiFyqz2ydaZA9ZkQBhDbzQCj+EQ4F57Yc4Px+wnZnbxSvjoK2A3b3aPYGZBhvZFR1G2r47fa-Y0j-b6YmEJStEQ4zHQ4Ygy76gypbwDaa4UTzHqgVQ+osQ2DoxkJSCML44y5cTCSriJElabgpEA5pFJgHHHg9Zni8Da5FgljgL7BHEVR5pxEP7DhbDgJXGS6rY6a56OhJ6F69FhDo5qBInPaRgABqaAcACQGwAgxMmoQYiwcSIBi4uy6oyBUgEJbug+ywaxOu2RDokJZQ9JkkDo1JUOcERIiEpoI+zBJEMyEg-JUBzhrhCQyiEAMk4ODJ9oD4a+ZByUdBceOxe8B+OoKpnc8pf+KkSscIpxyw-BtgNBupwp1Bupp+0ICBMASBYAKBaBWEmBt+yQCgig+B2p4kgAfBuACfuwqeQSaQqTQXQaaSwaKQkMGTQYKewQwc8sGVPuFJhNhGQLfkiRgTqG6Rvv-g4b6T8crOqFKaXmyXKdmYiHHJvPRGCIQLCAAHK0AB4Yj4BEj3Bs58DdRSggQ0GVlX7iSxmUQgDfi-hJTITukqQrjZhxj0SAS7RB4yCRATm-jASiAyAxFBpqmCRBoyC-4ZnHiBTDnJQaAOE9k0HhSHnxln4gBImX5pQMEaAxkj6blWgcliqqzcGSatTIDdiCE9SkCUCiFDTqbKGWFVBqFA7nwg5aH2BBARZWZ+aGH2ZHESAuZYKxbEB+Hg7JZkKVGbafZLYSilFIFDzLnCQJGhgbiRgvHlabZVZZY5aiZIUNFmA9YrgDZrHtHg4fEnhN6gULEwnWEA4gVOarFsXQm0m8ke5ghZoyo6jhnxmyqJnYGxHBoKFgCHlKnUQRCql9lJRAnBAglwDBAsnSmQRalbnJTmlwFWk2l2noGOmqCGwTDpmQHsSAAy5LwIAPB-AZFBWoh5tBgB9Bf+R56E0l6ECZOEqg3YU6fIDl1BlZIA9JY5fIUgHZ4ZYUgVd5ElPqHBtFmAUgXwQAA)
- [CodeSandbox](https://codesandbox.io/s/solid-create-event-dispatcher-example-fbj9ge?file=/src/feed.tsx) (here we can play with typescript better as types are imported)

**Comment by thetarnav** [comment]
Hey! Thanks for the proposal!
Could you please explain the advantages of this primitive over just calling a function prop? I can't find a reason for this here nor in the svelte docs.
I could see a value if the events were dispatched on an element and bubble, so they could be captured higher in the tree. But they aren't, which confuses me, because I usually align custom events with DOM elements. Having an option to dispatch it on an element would potentially be a nice feature.
The `cancelable` prop is intriguing though..
What's the pattern for manually dispatching/cascading the events up the tree? Then the `defaultPrevented` param will be useful there.

**Comment by AyloSrd** [comment]
Hey, thank you for the quick reply and the invitation to discuss it on discord!
I have joined the channel and addressed some points there!

**Comment by AyloSrd** [comment]
Hi @thetarnav, I was thinking a lot of you point of dispatching/and cascading events on the tree, and I was wondering if adding the possibility to trigger the event from the parent (instead of just passing an event handler and triggering the event from the child), would be useful?

Since in the DOM we dispatch events on an element and not from within it, for the primitive to be consistent with the DOM equivalent, it should enable this:
```js
// DOM dispatchEvent
element.dispatchEvent(new CustomEvent('testEvent', { detail: 42, cancelable: true })
```
```js
// The primitive  (used in the Child component) should enable this beahvior from its parent
Component.dispatch('testEvent', 42, { cancelable: true })
```

I would keep the current dispatch function (maybe rename it "emit", like in vue) and change a bit the primitive to look something like this from within inside the child component:
```js
// in the child
const [emit /*the old "dispatch"*/, dispatchable] = createComponentEvent(props)
// dispatchable should return the handler, so that it can be used alsoby the child compoment
const handleAnswer = dispatchable(evt => console.log(evt.detail + 42), 'answerEvent')
```
```js
// from the parent
Child.dispatch('answerEvent', 'The answer is ') // will cause the child to log 'The answer is 42'
```
To me it could come in handy, as today the only way I can think of for triggering an event on children components is to pass a signal prop and observe it via CreateEffect like so (e.g. I want to trigger the focus of a custom input): 
```jsx
// from the parent component
const [triggerFocus, setTriggerFocus] = createSignal(0)
return (
	<button onClick={() => setTriggerFocus(triggerFocus + 1)}>focus</button>
	<CustomInput triggerFocus={triggerFocus()} />
)
```
```js
// in the child
createEffect(() => {
	inputRef.focus()
}, props.triggerFocus)
```
Does it make sense to you ? 
Do you think it would be a useful enhancement or is the idea too farfetched ?

**Comment by atk** [comment]
I just had an idea: we could add an eventMapper directive that received an objects with event names and a string or array of strings with the name(s) of custom events it should be mapped to. It would look like this:

```js
<button use:eventMapper={{click: 'subscribe'}}>
```
Clicking the button then dispatches the custom subscribe event. Do you think this could be a helpful addition?

**Comment by thetarnav** [comment]
@AyloSrd I would avoid any attempt to "instanciate" the components—component is just a function returning HTML Elements, so this syntax doesn't sit well with me:
```ts
Child.dispatch("event")
```
Not sure how would that work too
Instead of focusing on components, we should be focusing on the primitives. And having a way to send events from parent to child is a good problem to solve, as the child -> parent is already covered by the `createEventDispatcher`.
The current way to do this is this:
```ts
const Parent: Component = props => {
   let handleToggle!: (state: boolean) => void

   onMount(() => {
      toggleListener(true)
   })

   return <Child handleToggle={listener => (handleToggle = listener)} />
}

const Child: Component<{ handleToggle: (listener: (state: boolean) => void) => void }> = props => {
   props.handleToggle(state => {
      console.log("new state:", state)
   })
   return <></>
}
```
When using the event-bus package it could be this:
```ts
import { createSimpleEmitter, GenericListen } from "@solid-primitives/event-bus";

const Parent: Component = props => {
   const [listen, emit] = createSimpleEmitter<boolean>();

   onMount(() => {
      emit(true)
   })

   return <>
      <Child handleToggle={listen} />
      <Child handleToggle={listen} />
      <Child handleToggle={listen} />
   </>
}

const Child: Component<{ handleToggle: GenericListen<[boolean]> }> = props => {
   props.handleToggle(state => {
      console.log("new state:", state)
   })
   return <></>
}
```

So I think that primitive for the parent -> child communication should follow a similar API design, but just use Custom Events as a payload.

**Comment by AyloSrd** [comment]
@atk I think it would be very useful! How would you pass the payload though?

@thetarnav Yep i agree, I shpuld'nt try to instanciate. Thx for the exemples, I think of  a similar way then
