### ISSUE TITLE
Move controlled props primitives from `props` package

### ISSUE THREAD

**Issue by thetarnav** [solidjs-community/solid-primitives#201]
The other primitives in this package do not ship jsx but are bundled to the same file. This requires users to put this package to `ssr.noExternal`, and causes the same on any dependent package.

**Comment by atk** [comment]
I'm fine with moving, but I'm not yet sure what name we should take for the new package. "prototyping" comes to mind. If you have a more suggestions, I'd like to hear them.

**Comment by thetarnav** [comment]
`controls`, `prop-controls`, `story`, `prototype`
they have a very specific use case, so a specific name might be fitting too

**Comment by edemaine** [comment]
`controlled-props` perhaps? (from the title of this issue)
This seems to fit `createControlledProps` (though it seems this may have been renamed to `createProps`? the root README says `createControlledProps`, while the `props` README says both in different places).
Also maybe fits with existing `event-props` package.

**Comment by thetarnav** [comment]
@atk do you have a favorite? :)
I'll probably be making the move soon

**Comment by atk** [comment]
I like controlled-props.
