### ISSUE TITLE
Broken Typescript types for `createStorage` -- forces all object keys to be the same type

### ISSUE THREAD

**Issue by nathanbabcock** [solidjs-community/solid-primitives#205]
Please correct me if I'm misunderstanding something here.

I see the type definitions for `createStorage` ([line 42 in `storage.ts`](https://github.com/solidjs-community/solid-primitives/blob/9c3774341eb6032bd016ab515a830330b0b79a07/packages/storage/src/storage.ts#L42))

This was my first attempt at using the library:

```ts
type MinimalTestType = {
  foo: string
  num: number
}
const [localStore, setLocalStore] = createLocalStorage<MinimalTestType>()
setLocalStore("foo", "asdf") // works
setLocalStore("num", 1) // type error, must be string
```

I expected it to work just like Solid Store. What happened?

Well, for one thing, the type parameter I passed in (`MinimalTestType`) was used as the type of the *options* object rather than the type of the object I am storing. That was already counter-intuitive, so next I tried the override `createStorage<O, T>` which lets you pass both the option type and the type of data to be stored. That results in a different problem:

```ts
const [localStore, setLocalStore] = createLocalStorage<{}, MinimalTestType>()
setLocalStore("foo", "asdf") // error -- expected "MinimalTestType"
setLocalStore("num", 1) // error -- expected "MinimalTestType"
```

Every single key of the object is now expected to match the type parameter. This does not match the API of the default Solid Store. I was expecting it to hold a single object of type `MinimalTestType`, use the setter to update it, and get the benefit of automatically writing the object to `localStorage` on changes. Please let me know if I'm misunderstanding how this library should be used. If you're open to contributions I'd like to take a stab at improving these type definitions to more closely match the calling conventions of Solid Store.

**Comment by nathanbabcock** [comment]
I ended up rolling my own version which follows the semantics and behavior of `createStore` almost exactly.

```ts
import { createStore, Store } from 'solid-js/store';

/**
 * Identical API to Solid Store, but wrapped with read/write to/from localStorage
 * 
 * @param key unique string identifier to use for localStorage
 * @param storeArg same as Solid Store
 * @param options same as Solid Store
 * @returns void
 */
export default function createLocalStore<T extends object>(
  key: string,
  storeArg: T | Store<T>,
  options?: {
    name?: string;
  },
): ReturnType<typeof createStore<T>> {
  // Fetch a previous value from localStorage, if it exists
  const localStorageRaw = localStorage.getItem(key)
  const localStorageParsed = localStorageRaw === null ? null : JSON.parse(localStorageRaw) as T
  const initialValue = localStorageParsed === null ? storeArg : localStorageParsed

  // Initialize the store with EITHER a saved value from localStorage,
  // or (as a fallback) the initial value passed in from storeArg
  // (localStorage always takes precedence if present)
  const [store, setStore] = createStore(initialValue, options)

  // Wrap the setter in a function that also writes to localStorage
  const setLocalStore: typeof setStore = (...args: any[]) => {
    const retVal = setStore(...(args as [any])) // ew https://stackoverflow.com/a/72450001
    localStorage.setItem(key, JSON.stringify(store))
    return retVal // void, but left in case of future changes
  }

  // Same return type as `createStore`
  return [store, setLocalStore]
}
```

**Comment by atk** [comment]
The browser Storage API requires keys to be string. You can use JSON.stringify as serializer and JSON.parse as deserializer in your options, then it should be supported.

**Comment by thetarnav** [comment]
I think those two (one in solid-primitives and @nathanbabcock's implementation) are completely different APIs. It's not only about the types. `createLocalStorage` in solid-primitives is more of a "reactive `localStorage`" with matching API, and the @nathanbabcock's `createLocalStore` is a solid's store that saves itself to localStorage. Similar to the one [here](https://www.solidjs.com/examples/todos).
So the types for our primitive aren't wrong. Each key-value pair is a different key-value pair in the storage. They reflect the `localStorage` API, but let you extend it with additional options for serialization and deserialization.
But that also means that we are missing an actual `createLocalStore` or `createStorageStore` that would let you just save the entirety of it's value under a single key in the storage, with utilizing fine-grained, single-property updates, and the rest of the store API. In a sense, it could be similar to the new `storage` option in the solid's `createResource`.

**Comment by nathanbabcock** [comment]
I think @thetarnav is totally right. If you think about `createLocalStorage` in solid-primitives as a reactive wrapper around `localStorage`, it makes perfect sense as-is. I was thinking of something totally different.

Thanks for the link to the Solidjs Todo example. I hadn't seen that one and the implementation is a little different (and cleaner) than mine. Notably they use `createEffect` instead of wrapping the setter.

 I realize now that what I'm thinking of is a whole different can of worms. You mentioned "fine-grained, single-property updates" which makes me wonder whether re-serializing the entire store at every change is wasteful -- perhaps there should be one key-value entry in localStorage _per property_ (including deeper levels of nesting, whose keys could be named with a path-like syntax). Implementing that would be tricky, if it's even worth doing.
 
Thank you for helping me clear up my confusion, it leaves me with some food for thought.
