### ISSUE TITLE
createCookieStorage cannot be explicitly typed

### ISSUE THREAD

**Issue by viridia** [solidjs-community/solid-primitives#231]
The storage object returned by `createCookieStorage` returns a `StorageObject<any>`. I wanted to get rid of the `any` and use a stronger type, so I tried this:

```ts
const [settings, getSettings] = createCookieStorage<IAppSettings>();
```

However, this doesn't work - the getter has the correct type that I would expect - it's type is `StorageObject<IAppSettings>`. However, the setter has the wrong type:

```ts
setSettings(key: string, value: IAppSettings)
```

In other words, the type signature is such that it wants you to pass the entire storage object instead of a single keyed value, which is inconsistent with how the function actually works.

What the setter ought to look like is something along these lines:

```ts
setSettings<Key extends keyof IAppSettings>(key: Key, value: IAppSettings[Key])
```

Also, I noticed that the docs say that you can use the cookie store "just like createStore", but this is not true - the setters produced by createStore have a lot more options (you can pass in a function etc.). Or at least, the TypeScript function signature for the setter doesn't have any of those options defined - you can only pass in a value.

So either these features should be added, or the docs corrected, because at the moment I was very confused when I tried to use the setters in that way.

**Comment by atk** [comment]
That doesn't work, because you are not using any (de)serialization, so all you can have is a Record<string, string>, because that's what Storage saves.

**Comment by viridia** [comment]
Without a deserializer, what storage saves is the string "[Object object]" which is probably not what you want. Perhaps the serializer should be mandatory instead of optional? (And it has to be an object, not a primitive type - because otherwise the proxy mechanism of stores wouldn't work.)

**Comment by atk** [comment]
Why should it be mandatory? If all you want to store is strings, that would be unnecessary overhead.

**Comment by thetarnav** [comment]
It matches the browser behavior by default. So nothing wrong here I think.

![image](https://user-images.githubusercontent.com/24491503/195014863-1fa9df23-b84e-410f-bfa2-1f9f6f3af769.png)

**Comment by atk** [comment]
Maybe the misunderstanding here is that we are not substituting createStore here, but instead abstracting the Storage standard into a primitive. I think we need better documentation.

**Comment by viridia** [comment]
Let me try and explain my confusion in more detail.

The documentation for createCookieStore says that it's a "reactive" store. Since the 'getter' value returned by createCookieStore is not a function, that means that the store has to be either an object proxy or an array proxy - there's no way for primitive values, by themselves, to be reactive. A store which was of type "string" could not be reactive. So the statement about the store being reactive caused me to make certain assumptions.

The documentation also states "is meant to wrap any localStorage-like API to be as accessible as a Solid Store". However, the API isn't much like a Solid Store from what I can tell.

Take for example my use case: I want to store a set of user preferences in a cookie. Since I like to strongly type everything, my preferences type looks like this:

```ts
interface Prefs {
  darkMode?: boolean;
  showSource?: boolean;
  selectedComponent?: string;
}
```

This is to be stored in a single cookie as a serialized object. So I'm assuming that I can access these preferences using a cookie store:

```ts
const [prefs, setPrefs] = createCookieStore(.../etc/...);
```

And I would access the prefs as follows:

```ts
if (prefs.darkMode) {
  // Render dark mode toggle with "dark" selected
} else {
  // Render dark mode toggle with "light" selected
}
```

OK so now I want to update the store when the user changes preferences, so I assumed it would be something like this:

```
setPrefs('darkMode', true);
```

...in other words, because the setter takes a key as the first parameter, I assume that key is the name of the property in the store object to be replaced. However, apparently that's not how it works. Instead, the second argument appears to be (according to the TypeScript type declarations) the *entire* store object, not just a single property.

If that is indeed the case, then I am not sure what the first argument means. If it's not the name of the property to be modified, then what is it? And if it is in fact supposed to be the name of the property, then the TypeScript function signature is wrong.

Now, in a regular Solid Store, there would normally only be one argument, which is merged with the store. So I would call:

```ts
setPrefs({ darkMode: true });
```

...which is very different from the API of the cookie store. In either case, it's important to be able to set single properties without knowing about the existence of other properties - the code for getting/setting dark mode should not need to know about the existence of other preference items - separation of concerns.

**Comment by atk** [comment]
Yes, as I said, it is not a regular Solid store, but an abstraction of the Storage API that is a web standard. I really need to update the docs. Also, we can probably also add a createStorageStore in this primitive as a simple abstraction.

**Comment by atk** [comment]
Since createCookieStorage is now deprecated, I'll close this issue.
