### ISSUE TITLE
`combineProps` not working in solid 1.6 when inline spreading

### ISSUE THREAD

**Issue by thetarnav** [solidjs-community/solid-primitives#235]
After upgrading Solid to 1.6 combineProps stopped working when called inline with the spread
```ts
// Pre Solid 1.6 
<span {...combineProps(a, b)} />

// Solid 1.6
const combined = combineProps(a, b);
<span {...combined} />
```

**Comment by Bubz43** [comment]
Even declaring it outside of the jsx still causes problems if you have any other attributes set after the combined spread.

[Playground](https://playground.solidjs.com/?hash=-1036572264&version=1.6)

The button with the type declared after the combined props spread only calls the last defined click handler.
