### ISSUE TITLE
@solid-primitives/keyboard TypeError: Cannot read properties of undefined (reading 'toUpperCase') 

### ISSUE THREAD

**Issue by pheianox** [solidjs-community/solid-primitives#246]
i use [@solid-primitives/keyboard](https://www.npmjs.com/package/@solid-primitives/keyboard) for shortcuts, but it shows some errors in console

in a component I have a shortcut like this
```ts
createShortcut(["Control", "K"], () => { ... })
```
in completely different component I have an input with a datalist
```ts
<input type="text" value={...} oninput={...} list="dataset" />
<dataset id="dataset">...</dataset>
```
when I choose an item from dataset two errors appear in the console
> screenshot from chrome console
![image](https://user-images.githubusercontent.com/77569421/199229595-f517a9a5-a9b2-4b16-86be-c37f07b9bff8.png)

> screenshot index.js from devtools
![image](https://user-images.githubusercontent.com/77569421/199229253-d3dc5939-3f6c-4999-852a-ee5009d6ddf1.png)

**Comment by thetarnav** [comment]
Interesting, I guess the `<datalist>` element emits keyboard events, but with `e.key` as `undefined`, even though the types for it say it has to be a string.
The only issue I could find on this is this: https://github.com/mdn/browser-compat-data/issues/9217, but it doesn't say much.
I guess I could check the `typeof e.key` before handling the event.
Thanks for reporting that!

**Comment by pheianox** [comment]
Yes, most likely the browser problem

Because I checked the app in Tauri which uses Microsoft Edge under the hood, and there were no errors
