### ISSUE TITLE
clipboard example does not work

### ISSUE THREAD

**Issue by pheianox** [solidjs-community/solid-primitives#256]
I wanted to copy simple text to the clipboard, but could not find out how

The example provided in the docs  does not work either something is broken
> docs: You may view a working example here: https://stackblitz.com/edit/vitejs-vite-okxns7

Is there a way to do something this simple
```ts
write("hello world")
```
When I do above it does not work for some reason

**Comment by sysmat** [comment]
Still not work, is this maintened?
