### ISSUE TITLE
@solid-primitives/scheduled leading is dropping trailing triggers

### ISSUE THREAD

**Issue by kaiserprogrammer** [solidjs-community/solid-primitives#282]
I guess this is the expected behavior since it mirrors normal throttle/debounce
but I would have more uses for it if trailing triggers would not be dropped.

4. leading
5. proposed leading

`    █   █       `
`------------------------>`
`4. █`
`5. █            █`

**Comment by thetarnav** [comment]
Yup, the current behavior is expected.
Although I'm open have another primitive variant that doesn't do this.

**Comment by atk** [comment]
Maybe an extra option to fire remaining changes on unmount?
