### ISSUE TITLE
[i18n] SSR

### ISSUE THREAD

**Issue by krulod** [solidjs-community/solid-primitives#307]
What is the best way to use `@solid-primitives/i18n` with SolidStart? Right now, it throws an error during server-side rendering:

```ts
ReferenceError: navigator is not defined
```

**Comment by thetarnav** [comment]
Thanks for the issue
The only `navigator` call I see is here and it is in the default param value. https://github.com/solidjs-community/solid-primitives/blob/main/packages/i18n/src/index.ts#L67
So right now to avoid it you probably should pass a lang param to not run it.
The package needs to be updated to not include browser APIs on the server though.
