### ISSUE TITLE
i18n - possibility to wrap strings with HTML?

### ISSUE THREAD

**Issue by tomexx** [solidjs-community/solid-primitives#317]
Is it possible to wrap chunks of i18n texts with HTML code, e.g. for hyperlinks, bold text and similar?

I'd need to use two hyperlinks in my i18n text:

```
ERROR_404_CTA: 'You can <a1>return to our front page</a1>, or <a2>drop us a line</a2> if you can\'t find what you\'re looking for.',
```

Thank you

**Comment by atk** [comment]
You can put the translated string into innerHTML. It's a potential security issue, though. Ideally, you use a delimiter to split the string and then use the parts in the JSX.
