### ISSUE TITLE
Re-run queries on header change?

### ISSUE THREAD

**Issue by bbqsrc** [solidjs-community/solid-primitives#328]
Hey!

I am setting a custom header in the `createGraphQLClient` function call. However, there does not seem to be a way to cause these headers to be reactive. Am I holding it wrong?

**Comment by thetarnav** [comment]
From what I see only the variables are being passed to the resource as sources, so only they can be tracked.
Reruning on headers or other options is not a usecase we espected, I don't think it's that common. I might be wrong though.
And I don't see an easy way to trigger it with the current API, so it should probably be considered in the design.

The implementation of `createGraphQLClient` is pretty simple if you reuse the `request` function, so you could create your own resource wrapper that handles it: https://github.com/solidjs-community/solid-primitives/blob/main/packages/graphql/src/index.ts#L44

Do you have some ideas on how this could be supported in our primitive?

**Comment by bbqsrc** [comment]
My use-case is when the user changes their language, I need to re-query to server to get localisation strings. Instead of having a language field everywhere in my GraphQL, I take advantage of the `Accept-Languages` header and try to have it that anything that is "linguistically enabled", reacts to changes to a language field in a global context.

I'm still quite new to Solid, so not entirely sure how to go about creating a resource wrapper, but the example you gave me should set me down the right track. 🙂

**Comment by bbqsrc** [comment]
So this worked:

```ts

const createGraphQLClient =
  (
    url: MaybeAccessor<string>,
    options?: MaybeAccessor<Omit<RequestOptions, "variables">>
  ): GraphQLClientQuery =>
  (query, variables: any = {}, initialValue) =>
    createResource(
      () => [access(variables), access(options)],
      ([vars, opts]) => {
        const variables = typeof vars === "boolean" ? {} : vars
        return request(access(url), query, { ...opts, variables })
      },
      { initialValue }
    )
```

Shall I make a pull request?

**Comment by thetarnav** [comment]
hmm, seems pretty simple 👍
I see that the `url` variable isn't reactive either, even though it is typed as `MaybeAccessor<string>`. So it could be fixed the same way.

> Shall I make a pull request?

yes please :)
