### ISSUE TITLE
`createElementSize` broken

### ISSUE THREAD

**Issue by vanillacode314** [solidjs-community/solid-primitives#375]
both signal and static ref version are broken
repro: https://stackblitz.com/edit/github-5vqsne?file=package.json%2Csrc%2FApp.tsx

I believe it is because of the recent static store refactor.

I updated from `2.0.12 => 2.0.14` when this bug appeared

**Comment by thetarnav** [comment]
Thanks, I think I was trying to bet on the ResizeObserver constantly firing a callback after the element gets observed, which seems not always to be the case. This should be an easy fix.
Btw something like this will never work:
```ts
let ref!: HTMLDivElement
createSomething(ref)
```
if almost always needs to be passed like this, or as a signal
```ts
createSomething(() => ref)
```

**Comment by thetarnav** [comment]
Fixed in https://github.com/solidjs-community/solid-primitives/commit/6fbee9717acc25be06607dbe45d88d9d68e6a6f4
