### ISSUE TITLE
[i18n] Cannot translate a string that includes a dot

### ISSUE THREAD

**Issue by gawlk** [solidjs-community/solid-primitives#382]
Hi !

It seems that translating a string having a `.` doesn't work.

Here a part of a dictionary that I give to `createI18nContext`
```
...
"N.S.": "x"
"N.S": "y"
"NS": "z"
...
```

And the results:

```
t("N.S.") -> undefined
t("N.S") -> undefined
t("NS") -> "z"
```

Not sure if the issue is with the library and an underlying dependency but thought I'd let you know

**Comment by thetarnav** [comment]
Seems like it was already brought up here: https://github.com/solidjs-community/solid-primitives/issues/257
It's an interesting issue because we use `.` dots as a way to go to a nested property in the path syntax.
Maybe this could be improved though.

**Comment by atk** [comment]
Why would you need a dot inside the key?

**Comment by gawlk** [comment]
@thetarnav I looked but didn't that issue, my bad

@atk We use the key as the default translation and thus the english one. We find it more complicated when we need to come up with both a unique key an English text if that makes sense. Sadly, it also removes the possibility to have sentences as keys.

**Comment by atk** [comment]
I already thought about a more composable solution that allows omitting features like nesting if required. Unfortunately, this will take a bit of time.

**Comment by gawlk** [comment]
@atk We'll wait then, thanks
