### ISSUE TITLE
autofocus: Does not work on component 2nd time even when using API correctly

### ISSUE THREAD

**Issue by nikitavoloboev** [solidjs-community/solid-primitives#383]
Using latest version of [@solid-primitives/autofocus](https://github.com/solidjs-community/solid-primitives/tree/main/packages/autofocus#readme).

I am trying to use it in [this project](https://github.com/nikitavoloboev/kuskus).

In theory I am doing exactly the same thing as the docs say. 

[Here](https://github.com/nikitavoloboev/kuskus/blob/main/src/components/NewTodo.tsx) is the component.

Ref and createAutofocus [here](https://github.com/nikitavoloboev/kuskus/blob/main/src/components/NewTodo.tsx#L12).

Then put it on input [here](https://github.com/nikitavoloboev/kuskus/blob/main/src/components/NewTodo.tsx#L39).

However when you load the app and press the plus button on the bottom, it will only autofocus the first time. The second time you press it, it will just do this:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/6391776/230460046-f77c7a95-d839-4b96-931c-b3ae07cce5f0.png">

I am not sure what's wrong. The weirdest thing though is that if I activate it through keyboard (press `n` key), it will always autofocus. I have no idea why.

**Comment by thetarnav** [comment]
This behavior wasn't caused by `autofocus` primitive but by an issue with the state management of your app.
Fix: https://github.com/nikitavoloboev/kuskus/pull/1
