### ISSUE TITLE
@solid-primitives/resize-observer not returning client bounds

### ISSUE THREAD

**Issue by jambudipa** [solidjs-community/solid-primitives#390]
I am struggling to get `@solid-primitives/resize-observer` to work.

Although `props.containerRef.getBoundingClientRect()` is reporting the correct bounds, when I use `createResizeObserver`, both `left` and `top` appear to be `0`.

Is it an offset from the parent? Here is a fragment of my code:

```
const Flowers: Component = (props: {containerRef: HTMLDivElement}) => {
  const [bounds, setBounds] = createSignal(null);
  const [particles, setParticles] = createSignal<Particle[]>([]);

  onMount(() => {
    const elementBounds = props.containerRef && props.containerRef.getBoundingClientRect();
    if (elementBounds) {
      setBounds(elementBounds); // <--- CORRECT
      console.log('elementBounds on mount', elementBounds);
    }
  });

  onMount(() => {
    createResizeObserver(props.containerRef, (b, element, entry,) => {
      if (element === props.containerRef) {
        console.log('DOMRect on mount', b); // <--- INCORRECT appears to be window bounds
        setBounds(b);
      }
    });
  });

  //...return something or other
}
```
If it is not expected to return the client bounding box, then fine: I will calculate that separately.

**Comment by thetarnav** [comment]
The first param of the `createResizeObserver`'s callback is the [`contentRect` property of `ResizeObserverEntry`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry).
Resize observer is only concerned with element size, so I wouldn't use it for getting the element position on the screen.
Calling `el.getBoundingClientRect()` in the callback to get the position should work fine.
But you may want to look at the [`createElementBounds`](https://github.com/solidjs-community/solid-primitives/tree/main/packages/bounds#createElementBounds) primitive that listens to more events then just the element resizing.

**Comment by jambudipa** [comment]
Excellent, thanks 🙏 Sent from my iPhoneOn 9 Apr 2023, at 11:52, Damian Tarnawski ***@***.***> wrote:﻿
The first param of the createResizeObserver's callback is the contentRect property of ResizeObserverEntry.
Resize observer is only concerned with element size, so I wouldn't use it for getting the element position on the screen.
Calling el.getBoundingClientRect() in the callback to get the position should work fine.
But you may want to look at the createElementBounds primitive that listens to more events than just the element resizing.
