### ISSUE TITLE
@solid-primitives/i18n: Struggling to implement HMR for locale definition

### ISSUE THREAD

**Issue by dvcol** [solidjs-community/solid-primitives#415]
### Describe the bug

Hello, 

I've written a small vite plugin that consolidate i18n files into a single definition, and i'm trying to implement HMR injection into an i18n context.

However, when I add a new locale definition to the context, the translate function accessed through useI18n doesn't seem to resolve the new value.

Here my context implementation: 

```typescript
import { createI18nContext, I18nContext as I18nSolidContext } from '@solid-primitives/i18n';

import type { ParentComponent } from 'solid-js';

type CreateI18nContextInputs = Parameters<typeof createI18nContext>;
export type I18nProviderProps = {
  initialDictionary?: CreateI18nContextInputs[0];
  initialLocale?: CreateI18nContextInputs[1];
};
export const I18nContext: ParentComponent<I18nProviderProps> = props => {
  const value = createI18nContext(props.initialDictionary, props.initialLocale);
  return <I18nSolidContext.Provider value={value}>{props.children}</I18nSolidContext.Provider>;
};

export default I18nContext;

```

And here is my HMR implementation:

```typescript
import { useI18n } from '@solid-primitives/i18n';

import type { Component } from 'solid-js';

export const I18nHmr: Component = () => {
  const [t, { add, dict }] = useI18n();

  if (import.meta.hot) {
    import.meta.hot.on('virtual:vite-plugin-i18n', ({ data }) => {
      if (data) {
        Object.keys(data).forEach(lang => {
          add(lang, data[lang]);
          console.info('setting', { lang, dic: data[lang] });
        });
        console.info('checking', { translate: t('routes.home'), dict: dict('en') });
      }
    });
  }

  return <div hidden aria-hidden="true" id="i18n-hmr" />;
};

export default I18nHmr;

```

I noticed when inspected the code that for some reason, the store proxy target seems to hold the new value, but acessing it return the original one (no matter how many HMR update are injected into the context).

![image](https://user-images.githubusercontent.com/17250935/233842782-2e2a03ee-29cf-4f27-9e2e-66c4a6c73f09.png)

I'm quite new to solid so I might be missing something, maybe it's a reactivity issue ?

The code is accessible [here]()

### Minimal Reproduction Link

https://github.com/dvcol/dvcol.github.io/compare/main...i18n-hmr

**Comment by thetarnav** [comment]
Hey, the i18n package was reworked recently.
The definitions of context and directories can now be kept in separate files easily.
The links that you've attached lead to nothing, so I can't really confirm what exactly was the issue or nor if it was fixed.
Also, if your plugin works with the package, feel free to link it in the readme, maybe someone will benefit from some additional tooling as well.

**Comment by dvcol** [comment]
Hello, thanks for the response !

After upgrading to the latest version I was able to fix the HMR issue. 

Unsure if it's due to the bump or the re-write (since the lib is a lot more low level now) but the reactivity works now 🤷 )

[The plugin](https://github.com/dvcol/vite-plugin-i18n) is more aimed at file merging i18n json difinition files more so than @solid-primitive/i18n  itself, not sure if it would be that relevant :)
