### ISSUE TITLE
Add `finish` method to Scheduled

### ISSUE THREAD

**Issue by ThaisRobba** [solidjs-community/solid-primitives#450]
### Describe The Problem To Be Solved

I have an input field and use debounce on the onInput to batch changes for undoing/redoing.
User can press Enter to submit data.
If User presses Enter before debounce finishes, I have to clear the debounce. This makes me lose the last value. So I have to track the value twice, one on the actual store that I'm using and one on a temporary signal and do this ugly thing:

```typescript
// Inside the submitInputHandler
triggerInputDebounce.clear();

// store.page.newNoteInput is the undo/redo tracked value
// newNoteInput is the throwaway signal
if (store.page.newNoteInput !== newNoteInput()) {
  setStore("page", "newNoteInput", newNoteInput())
}
```

### Suggest A Solution

I suggest adding a `finish` method to Scheduled, similar to what we see in animation libraries and whatnot.

Ideally it would just
1. Call the callback that was passed and
2. Call clear - which does the correct bookeeping already, so a rather small change ^^

```typescript
const finish = () => {
  callback();
  clear();
}
```

The problematic use case above would get much simpler:

```typescript
// Inside the submitInputHandler
triggerInputDebounce.finish();
// Done, so pretty 🥹
```

I'm available to work on it and submit a PR ^^

**Comment by thetarnav** [comment]
Ok this is a fair feature request I think. It can reduce the boilerplate of implementing this pattern:

```ts
//
// before
//
const saveNewNoteInput = (input: string) => {
	setStore("page", "newNoteInput", input)
}

const triggerSaveNewNoteInput = debounce(saveNewNoteInput)

// debounced
triggerSaveNewNoteInput("foo")

// forced
triggerSaveNewNoteInput.clear()
saveNewNoteInput("foo")


//
// after
//
const saveNewNoteInput = debounce((input: string) => {
	setStore("page", "newNoteInput", input)
})

// debounced
saveNewNoteInput("foo")

// forced
saveNewNoteInput.finish("foo")
```

I find myself using this from time to time to execute a priority task as soon as possible, while deferring others, so I can get behind this.

But reducing the boilerplate is **the only** benefit here. Unlike `.clear()`, this pattern is entirely implementable in the userland, and we usually tend to provide smaller but composable API surface, omitting features that do not need access to the internals.

Adding another method is increasing the bundle size for everyone, even if one is not using it. And it has to implemented for every single primitive as we are extending the `Scheduled` interface.

We could include this as a "How to" segment in the readme, with a snippet to copy.
It could be implemented as shown above, or by making a wrapper I think, similar to how `leading` works.

```ts
const debounced = withForce((fn) => debounce(fn, 1000), fn)
debounced.force()
```

> If User presses Enter before debounce finishes, I have to clear the debounce. This makes me lose the last value. So I have to track the value twice, one on the actual store that I'm using and one on a temporary signal and do this ugly thing

Could you explain how are you loosing the last value? I didn't understood this part. Maybe you could make a playground demo of the issue?

> I suggest adding a `finish` method to Scheduled, similar to what we see in animation libraries and whatnot.

"finish" reads for me as "immediately call the callback if one is pending", but your implementation will call it even if the callback is not currently scheduled for execution. So maybe not the best name, or we are looking at two different features.

How would it interact with `leading`? If the callback is already fired, intuitively I would say that `.finish() === .clear()`, but that would mean that the method would do different actions depending on the scheduler.

> I'm available to work on it and submit a PR ^^

I think that this feature needs to be thought through a bit more, but it is interesting. But if you don't mind the PR getting closed if we decide to drop the idea or do it differently, we could see how the implementation would look like if done your way.

**Comment by ThaisRobba** [comment]
> But reducing the boilerplate is the only benefit here. Unlike .clear(), this pattern is entirely implementable in the userland, and we usually tend to provide smaller but composable API surface, omitting features that do not need access to the internals.

> Adding another method is increasing the bundle size for everyone, even if one is not using it. And it has to implemented for every single primitive as we are extending the Scheduled interface.

Ah, that is fair, I hadn't thought about it as far as bundle sizes and whatnot. I think an addition to the documentation would be a good compromise ^^ 

> Could you explain how are you loosing the last value? I didn't understood this part. Maybe you could make a playground demo of the issue?
I "lose" in the sense that if I wait for debounce to complete and it happens *after* submission, history will be out of order so I have to explicitily ensure that it is saved. I made a small demo: https://codesandbox.io/s/stoic-lichterman-00c0mh?file=/src/index.jsx

Try inputting something like "abc", wait for it to show in history, then type something else and hit enter without waiting for debounce.

https://github.com/solidjs-community/solid-primitives/assets/597287/b4a0f029-eff6-4786-84de-381ee078a662

> How would it interact with leading? If the callback is already fired, intuitively I would say that .finish() === .clear(), but that would mean that the method would do different actions depending on the scheduler.

Yep, indeed that would be the case :-/

**Comment by ThaisRobba** [comment]
I feel like it really could just be in the docs. I did a crude/fast implementation that worked quite nicely ^^
I kept the same interface so it is a drop-in replacement 

```typescript
const debounceWithFinish = (callback, time) => {
  const trigger = debounce(callback, time);
  let scopedValue;
  
  function debounced(newValue) {
    scopedValue = newValue;
    trigger(newValue);
  }

  debounced.finish = () => {
    trigger.clear();
    callback(scopedValue);
  };

  debounced.clear = trigger.clear;

  return debounced;
};
```

There is probably a better way to do it, I'm not the best when it comes to library code/examples. I feel like having an example like this would really help without complecting the codebase ^^
