### ISSUE TITLE
@solid-primitives/storage: `sync` does not work as expected

### ISSUE THREAD

**Issue by whytspace** [solidjs-community/solid-primitives#457]
### Describe the bug

I wanted to use the [`sync` option](https://solid-primitives.netlify.app/package/storage#options) to keep a symbol synchronized between multiple tabs / windows.

My understanding was that if something updates the entry in local storage the symbol would be updated too. Unfortunately it is not.

### Minimal Reproduction Link

https://stackblitz.com/edit/solidjs-templates-awid8p?file=src%2FApp.tsx

- the local storage entry `test` is initialized with `string "foo"`
- the current value of the symbol is rendered
- the first button updates the symbol
- the second button updates the local storage entry 

#### Expected Result

When clicking the second button, the symbol should change. It does not. Refreshing the page is required for it to update

**Comment by atk** [comment]
As I understand the standard, we only get an event if the mutation happens out of our scope. For your use case, use a message channel sync instead.

**Comment by whytspace** [comment]
Just for clarification:
Sorry for the bad reproduction case. My issue is actually about sync not working at all (usinfg the setter method) when you have *two different tabs/windows" with the same app open.

When I update the local storage in Tab 1 (first button), the value in Tab 2 is not updated.

The idea with the reprodution sandbx was to open it in two different tabs and click on the first button on Tab 1.
My expectation of `sync` was that on Tab 2 the value would be updated, but it is not.
So `sync: true` is the same behaviour as `sync: false`.

In this Video I am clicking on the button that calls the setter function, but the Value in the other tab is only refreshed once I reload the page.
https://github.com/solidjs-community/solid-primitives/assets/4341219/993d04ae-f8ba-4ca7-a286-43581c57a9f3

**Comment by atk** [comment]
You misunderstood the API. You are supposed to put a sync-API into options.sync, e.g. `{ sync: storageSync }`.

**Comment by whytspace** [comment]
Ah, now I understand. Sorry for the troubles 😀

**Comment by atk** [comment]
It's okay. This shows that we can improve in terms of documentation, so no harm done.
