### ISSUE TITLE
A primitive for type-checking in places we know a computed value will be defined for a semi-defined computed value.

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs-community/solid-primitives#465]
### Describe The Problem To Be Solved

Example:
Say we have a drawing app that has a floating UI for the length/angle of the line segment currently being drawn with the mouse. When the mouse goes outside the drawing area, the length/angle will take on the value undefined. When the mouse is inside the drawing area the value will be defined. Also we do not want the DOM elements to be recreated every time the length/angle changes from a defined value to a defined value. Most the time length/angle are defined.

### Suggest A Solution

Suggested primitive:
```
export function memoFilterDefined<A>(a: Accessor<A | undefined>): () => Accessor<A> | undefined {
    // has() only triggers when value changes from defined to undefined or via versa, not from some defined to some defined.
    let has = createMemo(() => a() != undefined);
    //
    return () => {
        // if undefined don't return the signal.
        if (!has()) {
            return undefined;
        }
        // if we reach here, the signal is always defined, so cast the type of the result.
        return a as Accessor<A>;
    };
}
```

Example Usage: ```lengthAngle``` has type ```Accessor<{ length: number, angle: number} | undefined>``` and is not included in example code.
```
let lengthAngleFilterDefined = memoFilterDefined(lengthAngle);
this.overlayUI = createMemo(() => {
    let lengthAngle2 = lengthAngleFilterDefined();
    if (lengthAngle2 == undefined) {
        return undefined;
    }
    return (
        <div>
            Length: { lengthAngle2().length } <br/>
            Angle: { lengthAngle2().angle }
        </div>
    );
});
```

Now the div element is not recreated fully every time the length/angle changes from a defined value to a defined value. However the content of the div will update as the length/angle changes. Only if the value goes from undefined to defined is the div element recreated fully.

This example is overkill, and won't make any different for a small UI dom. But for a larger one it might.

Also this primitive only makes sense in TypeScript, not JavaScript. Because if you reach a spot in your code you know your value is always defined, there is no type checker to suggest otherwise. And it only works if ```lengthAngle2``` is not assigned to a variable outside the ```createMemo``` (root) of ```this.overlayUI```, so it needs to be used in a certain way. I'm open to other ideas to achieve the same desired effect.

**Comment by thetarnav** [comment]
This looks like `<Show>` in primitive form, which doesn't seem so bad.

**Comment by clinuxrulz** [comment]
I'll close this. I can not guarantee type safety (filtered memo used outside scope)

**Comment by thetarnav** [comment]
`<Show>` has the same issue if you read the 1.7 release. Solution there is to throw if the narrowed signal is read when the condition isn’t met.

**Comment by clinuxrulz** [comment]
Had a look at those 1.7 release notes, and ```<Show>``` is exactly what I want. I wasn't aware you can pass a function to ```<Show>```  to narrow down the type.

Thanks.
