### ISSUE TITLE
Use `contentBoxSize` and `borderBoxSize` instead of `contentRect` in `createElementSize`

### ISSUE THREAD

**Issue by nonphoto** [solidjs-community/solid-primitives#469]
### Describe The Problem To Be Solved

See [resize-observer line 177](https://github.com/solidjs-community/solid-primitives/blob/696caab173421c4be698b267530e8f5b74bbb515/packages/resize-observer/src/index.ts#L177). MDN describes this property:

> Note that this is better supported than the above two properties, but it is left over from an earlier implementation of the Resize Observer API, is still included in the spec for web compat reasons, and may be deprecated in future versions.

`contentBoxSize` and `borderBoxSize` would allow you to choose between content and border boxes which is would be useful for people who use `box-sizing: border-box` on everything (like myself).

### Suggest A Solution

I thought of two solutions:

1. Add a flag to `createElementSize` to specify which box sizing to use.
2. Detect the box sizing from the element's computed styles.

**Comment by thetarnav** [comment]
Looking at the [ResizeObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry) I'm not sure if this should be even used at all.

![image](https://github.com/solidjs-community/solid-primitives/assets/24491503/e8bebbca-6ed1-439e-bbd2-b59a840e0bf6)

`blockSize` and `inlineSize` properties of `contentBoxSize` and `borderBoxSize` items depend on text direction, which is probably not what you want.
And `contentRect` is not consistent with `el.getBoundingClientRect()` as you are pointing out. And we are using the elements bounding rect size as the initial signal value.

I think it's best to just use `el.getBoundingClientRect()` at all times, as this is value mostly used for calculations that need el size, and not complicate the primitive with ways to overwrite the values.
