### ISSUE TITLE
Allow optional number in input-mask

### ISSUE THREAD

**Issue by TiLopes** [solidjs-community/solid-primitives#471]
### Describe The Problem To Be Solved

Currently the user is forced to fill the input-mask, but if we are talking about phone numbers they have different amount of digits. This makes this package basically useless when it comes to this type of problem where there may be some optional part in the input.

### Suggest A Solution

I've seen other libraries in other frameworks (Angular: ngx-mask) which have 0 as a mandatory number to fill while 9 is optional.
Example of ngx-mask:
![image](https://github.com/solidjs-community/solid-primitives/assets/106965010/782ac607-6808-4853-bf62-fa199cc1bfa5)

**Comment by atk** [comment]
I think I would prefer to have 0/O as optional, since 9/X are already used for numbers and letters and I would like to stay compatible. In the meantime, you could probably use the array form.

**Comment by atk** [comment]
I'll have a solution ready soon.

**Comment by atk** [comment]
Sorry, I was sick in the last few weeks. The solution was just merged, I expect it to be released soon.
