### ISSUE TITLE
[storage] `cookieStorage` doesn't work with Solid-Start

### ISSUE THREAD

**Issue by yume-chan** [solidjs-community/solid-primitives#480]
### Describe the bug

When using `cookieStorage` with `makePersisted`, the server console always prints "It seems you attempt to use cookieStorage on the server without having solid-start installed".

Workaround: Copy https://github.com/solidjs-community/solid-primitives/blob/d74956b93850672afcb519d917ca9b08e9457362/packages/storage/src/cookies.ts into my project and convert `require("solid-start/server")` to a normal top level `import`.

### Minimal Reproduction Link

https://stackblitz.com/edit/github-n4ho5j-u5pz4k?file=src%2Froutes%2Findex.tsx

**Comment by atk** [comment]
The code you've shown is executed both on the server and the client - and it seems that the server import for useRequest fails. If you want it to only store cookies on the client in solid-start, you need to `import isServer from "solid-js/web"` and use

```ts
const [value, setValue] = isServer
  ? createSignal("initial")
  : makePersisted(
      createSignal("initial"),
      { name: "value", storage: cookieStorage, storageOptions: { path: "/", maxAge: 60 * 60 * 24 * 7 } }
    );
```

**Comment by yume-chan** [comment]
> If you want it to only store cookies on the client in solid-start,

No, I want to read the value on SSR, that's why I used `cookieStorage`, but it doesn't work.

**Comment by atk** [comment]
Understood.

**Comment by atk** [comment]
I think I have an idea. It reduces the convenience a bit, but on the other hand makes it far more flexible: I'll accept a requestAccessor (that either returns Request or, like useRequest, { request: Request }) and a cookieSetter as optional options.

**Comment by yume-chan** [comment]
https://github.com/solidjs/solid-start/blob/e83271fef5469b4e4e986566f8d07e84388558c9/packages/start/server/ServerContext.tsx#L7-L13

```js
export const useRequest = () => {
  return useContext(ServerContext)!;
};


export const useServerContext = () => {
  throw new Error("useServerContext is deprecated. Use useRequest instead.");
};
```

I think `useServerContext` is the old name and no longer be used.

**Comment by atk** [comment]
Thanks, the docs are still on the old name. In any case, even though it should work out of the box in other cases than stackblitz, you can use the getRequest option to give useRequest to makePersisted manually and it will no longer rely on the attempted optional import that breaks in stackblitz - after [PR ](https://github.com/solidjs-community/solid-primitives/pull/482) is merged and released.

**Comment by atk** [comment]
This should no longer be an issue, since require is called in a try-catch block. You can still supply it in the getRequest option if you actually use the new version from PR#482 (https://github.com/solidjs-community/solid-primitives/blob/92041fd34e6113e9789256a651a0f31859dfa0da/packages/storage/src/cookies.ts):

```ts
const [value, setValue] = makePersisted(
      createSignal("initial"),
      {
        name: "value",
        storage: cookieStorage,
        storageOptions: { path: "/", maxAge: 60 * 60 * 24 * 7, getRequest: useRequest }
      }
    );
```

**Comment by yume-chan** [comment]
Yes, I can supply `getRequest` with the new option. However, the try-catch block will never success, my StackBlitz repro is using **Solid-Start template, not Solid**, and it doesn't work.

**Comment by atk** [comment]
That should not be an issue, even with the try-catch block failing, as the function you supply in getRequest will override the useRequest that could not be loaded.

**Comment by mb21** [comment]
btw. related issue for using localStorage: https://github.com/solidjs-community/solid-primitives/issues/501
