### ISSUE TITLE
[storage] `cookieStorage` throws error for first request

### ISSUE THREAD

**Issue by yume-chan** [solidjs-community/solid-primitives#481]
### Describe the bug

When using `cookieStorage` with `makePersisted` (after applying the workaround in #480), it throws `Cannot read properties of null (reading 'match')` for requests without Cookie.

That's because `useRequest().request.headers.get("Cookie")` returns `null` if the request doesn't have a Cookie header.

### Minimal Reproduction Link

https://stackblitz.com/edit/github-n4ho5j-4s9dwz?file=src%2Fcomponents%2Fcookies.ts,src%2Froutes%2Findex.tsx

**Comment by atk** [comment]
You used the old version of the script, not the one from the PR. Also, please let's use issue#480 to track the problem and not create new ones for the same thing.

**Comment by yume-chan** [comment]
This is a different issue, and #482 doesn't fix it. The `Cannot read properties of null (reading 'match')` error was thrown here:

https://github.com/solidjs-community/solid-primitives/blob/d74956b93850672afcb519d917ca9b08e9457362/packages/storage/src/cookies.ts#L73-L75

When `_read` returns `null`.
