### ISSUE TITLE
String Extraction CLI Tool for `@solid-primitives/i18n`

### ISSUE THREAD

**Issue by BierDav** [solidjs-community/solid-primitives#492]
### Describe The Problem To Be Solved

As a developer it would be nice to just use the t method with a default value for development and afterwards extract all the resources to json files using a cli tool. So that i can translate my app afterwards and be sure not to have missed a key.

### Suggest A Solution

Create a built-in CLI Tool that allows extracting all the keys also considering `useScopedI18n` with default value for a defined default language to dedicated .json files.

**Comment by thetarnav** [comment]
I don't think that a cli tool is right for this project.
Better place for this would be [solid-cli](https://github.com/solidjs-community/solid-cli) or [mediakit](https://github.com/solidjs-community/mediakit)
