### ISSUE TITLE
Add an options to turn on `isIdle` manually

### ISSUE THREAD

**Issue by itamarsch** [solidjs-community/solid-primitives#503]
### Describe The Problem To Be Solved

In my application when the screen is Idle I display a series of animations. Once `onActive` is called I stop those animations

I want to trigger those animations manually on some event but I still want the `onActive` function to stop those animations once the mouse moves (or any other event that triggers `isIdle` happens)

### Suggest A Solution

The easy solution for this would be a `triggerIdle` function which would be the opposite of `reset`

**Comment by thetarnav** [comment]
`createIdleTimer` returns various methods from what I see:

![image](https://github.com/solidjs-community/solid-primitives/assets/24491503/a044fed2-2784-4dc0-ba4a-bac40e5f306d)

Don't you have a full control over the state of listeners with these?

**Comment by itamarsch** [comment]
> `createIdleTimer` returns various methods from what I see:
> 
> 
> 
> ![image](https://github.com/solidjs-community/solid-primitives/assets/24491503/a044fed2-2784-4dc0-ba4a-bac40e5f306d)
> 
> 
> 
> Don't you have a full control over the state of listeners with these?

You have control of the listeners but you still can't achieve the behavior I want which is telling the library that the app is currently idle.

The control of the listeners only let's you disable them and start them

**Comment by AyloSrd** [comment]
@itamarsch If I understand correctly, you would like a triggerIdle function that sets isIdle to true, triggers the onIdle callback, and attaches a listener to the events that will call onActive if triggered, correct?

This request makes sense to me, as it serves a similar function to the ImmediateEvents prop in React Idle Timer but provides more flexibility to the user in specific use cases (for example, when the user clicks a 'lock' button).

@thetarnav  If you are in agreement with this, I would be willing to open a pull request to implement the requested change. Additionally, I would take this opportunity to rewrite the JSDoc, as I wasn't familiar with it when I initially wrote them, and they could be improved.

**Comment by thetarnav** [comment]
Yeah I think it makes sense to allow this kind of interactions. Even if the primitive is designed to detect user idleness through other means, you should still be able to override that, by having access to all the state and functions.

**Comment by AyloSrd** [comment]
Perfetct, thx; I am on it
