### ISSUE TITLE
@solid-primitives/filesystem async data is not resolved

### ISSUE THREAD

**Issue by asaf** [solidjs-community/solid-primitives#526]
### Describe the bug

Hey,

`AsyncFileSystem` returns data before it's been resolved,

For example the `readFile` method uses [createResource](https://github.com/solidjs-community/solid-primitives/blob/main/packages/filesystem/src/reactive.ts#L189) to fetch the data asynchronously, while being fetched `data()` is returned but returns null value.

I'm new to Solid so not sure where reactive ends but as it seems like `data()` is not reactive,

Second call works as data is already resolved,

This behaves the same for all methods,

Best,
Asaf.

### Minimal Reproduction Link

https://primitives.solidjs.community/playground/filesystem

**Comment by asaf** [comment]
I opened this too soon, `data()` is reactive as long as the fileSystem API is invoked in solid flow, I tried to invoke it inside a func that is not reactive.

**Comment by atk** [comment]
Still, thank you for showing that our documentation could still be improved.
