### ISSUE TITLE
[storage] `cookieStorage`'s `maxAge` option doesn't work

### ISSUE THREAD

**Issue by yume-chan** [solidjs-community/solid-primitives#530]
### Describe the bug

Create a persisted signal using `cookieStorage` and passing the `maxAge` option, but the created cookie is a session cookie.

In the linked StackBlitz project, click "Open in New Tab" button at top-right corner. Looks like it can't set cookies from an iframe.

```ts
  const [maxAge, setMaxAge] = makePersisted(createSignal('initial'), {
    name: 'maxAge',
    storage: cookieStorage,
    storageOptions: { path: '/', maxAge: 60 * 60 * 24 * 7 },
  });
  const [expires, setExpires] = makePersisted(createSignal('initial'), {
    name: 'expires',
    storage: cookieStorage,
    storageOptions: {
      path: '/',
      expires: new Date(Date.now() + 60 * 60 * 24 * 7 * 1000),
    },
  });

  createEffect(() => {
    setMaxAge('hello');
    setExpires('hello');
  });
```

![image](https://github.com/solidjs-community/solid-primitives/assets/1330321/628d7322-ecbd-42ab-8c44-d4b6942d00a8)

### Minimal Reproduction Link

https://stackblitz.com/edit/github-n4ho5j-nffe5j?file=src%2Froutes%2Findex.tsx

**Comment by sh1man999** [comment]
I confirm this error

**Comment by apatrida** [comment]
The problem is `serializeCookieOptions` doesn't convert `maxAge` to `max-age` and other similarly named object properties that do not match the name of the attribute expected by the browser.
