### ISSUE TITLE
@solid-primitives/context MultiProvider does not support SSR

### ISSUE THREAD

**Issue by asaf** [solidjs-community/solid-primitives#540]
### Describe the bug

Using `MultiProvider` with SSR causes:

`Cannot read properties of undefined (reading '0')`

Specifically failing on `let item = values[i];` line

```js
function MultiProvider(props) {
  const { values } = props;
  const fn = (i) => {
    let item = values[i];
    if (!item)
      return props.children;
    const ctxProps = {
      get children() {
        return fn(i + 1);
      }
    };
    if (Array.isArray(item)) {
      ctxProps.value = item[1];
      item = item[0];
      if (typeof item !== "function")
        item = item.Provider;
    }
    return createComponent(item, ctxProps);
  };
  return fn(0);
}
```

### Minimal Reproduction Link

todo

**Comment by thetarnav** [comment]
> `Cannot read properties of undefined (reading '0')`

That means `props.values` is undefined. Which shouldn't have anything to do with SSR.
So I'm not sure whether the issue is in the library or your code.

But the tests for ssr are missing anyway so that needs to be added.
