### ISSUE TITLE
mouse typings should support SVGSVGElement as target

### ISSUE THREAD

**Issue by edemaine** [solidjs-community/solid-primitives#543]
### Describe The Problem To Be Solved

`@solid-primitives/mouse` currently restricts the `target` to be (an accessor of) `HTMLElement | Window | Document`. I'd like the typings to include `SVGSVGElement` (and maybe all/more of `SVGElement`), which works fine in my testing.

### Suggest A Solution

The docstring actually says `Element` instead of `HTMLElement`, but this doesn't match the typings of `@solid-primitives/event`. I couldn't quite decipher the `TargetWithEventMap` magic to make this work out, but ideally you could use the same typings from there.

**Comment by thetarnav** [comment]
Fixed in https://github.com/solidjs-community/solid-primitives/commit/7e7888a22adcc39b67968af41f947caa4186fb60
`Element` cannot be used, it has only `"fullscreenchange"` and `"fullscreenerror"` available events.
