### ISSUE TITLE
Make i18n work with JSX

### ISSUE THREAD

**Issue by BierDav** [solidjs-community/solid-primitives#550]
### Describe The Problem To Be Solved

Currently, there is no way how to format an i18n value. For example, you have a user variable, and you want to display the user in bold. Like this
```
"complete_registration_subtitle": "Hi <b>{{ name }}!</b"
```

This currently doesn't work.

### Suggest A Solution

I propose that all translations should return JSX so that such formatting can be done.

**Comment by thetarnav** [comment]
you can do this
```tsx
"complete_registration_subtitle": () => <>Hi <b>{{ name }}!</b><>
```
or
```tsx
<div innerHtml={t.complete_registration_subtitle()} />
```
or create a custom template resolver that parses html and returns html elements.

**Comment by BierDav** [comment]
Unfortunately this causes weird issues with solid start (or seroval 🙂) on the latest available version 0.3.10:

```
Error
Seroval caught an error during the parsing process.
  
Error
The value [object Function] of type "function" cannot be parsed/serialized.
      
There are few workarounds for this problem:
- Transform the value in a way that it can be serialized.
- If the reference is present on multiple runtimes (isomorphic), you can use the Reference API to map the references
```

**Comment by thetarnav** [comment]
Thats interesting. To be honest I have no idea what solid start chooses to serialize and what not, I don't think the i18n lib is doing anything wring, in the end you are just calling a function and getting some values back, and here the values happen to be html elements.
A reproduction would be helpful regardless if this is an issue with solid start or solid primitives.

**Comment by BierDav** [comment]
Here you go: https://stackblitz.com/~/github.com/BierDav/solid-primitives-i18n-bug

The problem is that createResource is not able to work with functions as result value I guess: https://github.com/BierDav/solid-primitives-i18n-bug/blob/e27d9bed2350c0c20800b6c6502318443a42d077/src/App.tsx#L18-L24

**Comment by BierDav** [comment]
`ssrLoadFrom: "initial"` fixes the issue for me, thanks for rubber ducking 🙈

**Comment by BierDav** [comment]
No, actually this is still an issue, because I don't want to use ssrLoadFrom: "initial", because I need to fetch the current language in ssr, I can't simply render everything in english.

**Comment by BierDav** [comment]
@thetarnav do you have an idea how to dynamically bundle the correct language files on ssr in the initial response, so that the client gets all the translations in it's first request. The problem is that createResource would allow that, but it sadly doesn't work with functions so my idea was to really import the files dynamically so that the get bundled directly into the ssr response. Is this even possible? I mean it should be, because createResource does a similar thing, but is it also possible for normal .ts and .tsx files?

If we come to a solution, I'm willing to create a full fledged tutorial how to implement i18n with solid start.

**Comment by thetarnav** [comment]
on the solidjs website we just default to english, it is the language that is always immediately available both on the server and client.
And other languages fetched dynamically.
Which should work fine with SSR, as th

**Comment by thetarnav** [comment]
I'm not sure if there is a way to include translations in the response if they cannot be serialized.

I would just lazy load the correct translations on the client.
You could maybe try adding a `<link rel="preload" as="fetch" href="lang-specific-translations" />` to html head to fetch it as soon as possible.
Or inline the whole module in a `<script type="module" />` tag. I'm not sure.

But for seroval and solid start to handle this automatically, and without requiring additional fetch on the client to get the translations, the translations would need to be serializable. Which means that returning functions is a no-go, and the "create a custom template resolver that parses html and returns html elements" is the best way to go.

Other, more manual, option would be to "serialize" values as arrays or objects `key: ["hello", "!"]` which then can be used in the template `<>{t.key[0]()}<b>{name}</b>{t.key[1]()}</>`.

Also the `innerHTML` solution should work fine, it's serializable.

Those are my ideas.
I'm also not sure if there is anything special that the primitives library could provide here.

**Comment by BierDav** [comment]
Thanks for your detailed answer, my approach to resolve the issue would be to build a custom template engine that allows also wrapper templates:
```
Hello {make_bold}{{ forename }} {{ lastname }}{make_bold_end}, you are logged in with {{ email }}. Go to {home_link}home{home_link_end}
```

The usage should look like this:

```
mytranslation({forename: "Foo", lastname: "Bar", make_bold: (inner) => (<b>{inner}</b>), home_link: (inner) => (<a href="google.com">{innner}</a>))

```

**Comment by thetarnav** [comment]
> The `TemplateResolver` returns a string and not JSX, therefore such an implementation is impossible without breaking the type system what I definitely won't do.

Yeah I'm noticing that now, this won't do. There isn't anything at runtime preventing returning other values than `string` - function fields can return anything, but a `string` just simplified types here.

It should be possible to tweak the types to allow `TemplateResolver` to be generic. If it can be done without too much complexity I'm down to add it.

Another option, instead of bending the primitives to that usecase (although a valid one), would be to just "fork" the library, reuse what can be reused, and and write your own translator function. In the end this library is just a single file with various function and type helpers that you put yourself together to create the api you want.

**Comment by BierDav** [comment]
Then lets exactly do that, thanks I haven't even though about adding generics even though it would be the most straight forward thing hahaha. I will make a pr.

Btw. I don't want to make my own version of all libraries, because on the one hand it is hard to maintain, when we want to get new features and secondly this is my way to contribute to open source :)

**Comment by BierDav** [comment]
@thetarnav can you please look at my pr?
