### ISSUE TITLE
`createEventListener` infers type `Event` on input event instead of `InputEvent`

### ISSUE THREAD

**Issue by Tronikelis** [solidjs-community/solid-primitives#558]
### Describe the bug

```tsx
let inputRef: HTMLInputElement | undefined;

createEventListener(
  () => inputRef,
  "input",
  (event) => {
    // event: Event here
    const target: HTMLInputElement = event.target;
  }
);
```

This should be input event with a target of HTMLInputElement I presume?

### Minimal Reproduction Link

https://codesandbox.io/p/sandbox/little-worker-pn5z2g?file=%2Fsrc%2Findex.ts%3A4%2C1-14%2C1

**Comment by thetarnav** [comment]
Well this has the same issue, so I'm not sure.
```ts
;({} as any as HTMLInputElement).addEventListener("input", (event) => {
  const target: HTMLInputElement = event.target;
})
```

**Comment by thetarnav** [comment]
Interestingly there is "beforeinput" that is typed as `InputEvent`
```ts
;({} as any as HTMLInputElement).addEventListener("beforeinput", (event) => {
  event // InputEvent
})
```

**Comment by thetarnav** [comment]
https://github.com/microsoft/TypeScript/issues/39925#issuecomment-669550088

I'm not gonna go against typescripts own types here unless there is a good reason.

Thanks for bringing it up though, thats very interesting.
