### ISSUE TITLE
type inference not working `@solid-primitives/destructure`

### ISSUE THREAD

**Issue by Enteleform** [solidjs-community/solid-primitives#569]
### Describe the bug

![image](https://github.com/solidjs-community/solid-primitives/assets/10906415/d32c757f-2a2f-414f-b0c8-60574271e892)

This example was taken from the documentation's [Spread component props](../tree/main/packages/destructure#spread-component-props) snippet.

### Minimal Reproduction Link

https://stackblitz.com/edit/github-14fosr?file=package.json&file=src%2FListItem.tsx

**Comment by thetarnav** [comment]
Tried the same code on stackblitz and locally and it was working fine

![Screenshot from 2024-09-13 09-03-30](https://github.com/user-attachments/assets/d774ba7a-16e5-4312-84c2-086680845423)

Maybe the issue is with ts version? I tested on 5.5 and 5.2, stackblitz is on 5.1.

**Comment by thetarnav** [comment]
Actually I got a similar error when updating typescript dependency, but it went away when restating the ts server.

**Comment by Enteleform** [comment]
Seems to be working now @ original repro and with [updated dependencies](https://stackblitz.com/edit/github-14fosr-vpk6pg?file=package.json&file=src%2FListItem.tsx).
