### ISSUE TITLE
workers package missing WorkerExports type in declaration file 

### ISSUE THREAD

**Issue by Kyran121** [solidjs-community/solid-primitives#594]
### Describe the bug

`WorkerExports` type is missing in the type declaration file when installing latest version of workers package.

![Screenshot_2024-03-26_at_19 50 59](https://github.com/solidjs-community/solid-primitives/assets/133128270/5035305f-e1e0-4df8-9256-ed57049d1f29)

### Minimal Reproduction Link

https://stackblitz.com/edit/github-2adggc?file=src%2FApp.tsx

**Comment by waynevanson** [comment]
Just imported this package and see the same.
