### ISSUE TITLE
Feature request / suggestion: makeCleanupSignal

### ISSUE THREAD

**Issue by knpwrs** [solidjs-community/solid-primitives#597]
### Describe The Problem To Be Solved

Various web platform features accept the signal from an `AbortController` to cancel or remove effects. It would be great to tie this into the Solid component lifecycle automatically.

### Suggest A Solution

I just implemented the following in my own project:

```ts
import { onCleanup } from 'solid-js';

export function makeCleanupSignal(condition = true) {
  const controller = new AbortController();

  onCleanup(() => {
    if (condition) {
      controller.abort();
    }
  });

  return controller.signal;
}
```

It's very simple, but allows for straightforward usage with web platform features (either ones that don't have primitives available, or when lower-level control is desired):

```ts
import { onMount } from 'solid-js';
import { makeCleanupSignal } from './util';

const signal = makeCleanupSignal();

onMount(() => {
  document.addEventListener('click', () => alert('Hey!'), { signal });
  fetch('//google.com', { signal }).then(/* */);
});
```

I would be happy to submit a pull request for this feature if such a feature would be desired. I'm open to other names as well so that `makeCleanupSignal` doesn't get confused with Solid signals.

**Comment by atk** [comment]
There's already makeAbortable in the resource package; maybe it can be extended to this use case.

**Comment by knpwrs** [comment]
I could certainly see `makeAbortable` being the basis for this function, but I'd personally be cautious about overloading the existing API for `makeAbortable` if that's what you're talking about.

**Comment by atk** [comment]
we could simply add `createAbortable` that does reactive cleanup.
