### ISSUE TITLE
Container queries

### ISSUE THREAD

**Issue by aryzing** [solidjs-community/solid-primitives#607]
### Describe The Problem To Be Solved

The [`media`](https://github.com/solidjs-community/solid-primitives/tree/main/packages/media) package works great! Could we add [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) as well?

### Suggest A Solution

Something like,

```ts
import { makeContainerQueryListener } from "@solid-primitives/media";

const clear = makeContainerQueryListener("my-container (width > 767px)", e => {
  console.log(e.matches);
});
// remove listeners (will happen also on cleanup)
clear();
```

**Comment by thetarnav** [comment]
Yeah that would make sense. Feel free to contribute it.
But is there a JavaScript API for container queries? The link you've sent is for a CSS feature.

**Comment by aquaductape** [comment]
There's no JavaScript API for container queries. The `matchMedia` API which solid-primitive/media uses, only applies for window not elements. The alternative is using [`resize-observer` primitive](https://primitives.solidjs.community/package/resize-observer).

The [CSS working group is discussing on adding `matchContainer`](https://primitives.solidjs.community/package/resize-observer), which is the JavaScript API for container queries, if it goes through, will still take years.

**Comment by aryzing** [comment]
Thanks both, closing then, we can revisit in a few years if still relevant
