### ISSUE TITLE
createAbortSignal support

### ISSUE THREAD

**Issue by fabiospampinato** [solidjs-community/solid-primitives#63]
It should be pretty useful to have a `createAbortSignal` primitive, that returns an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) that's automatically aborted when the parent computation is disposed.

**Comment by thetarnav** [comment]
No comment from me on the idea of a new package as I never used this api before. But if you didn't know, the [`createFetch`](https://github.com/davedbase/solid-primitives/tree/main/packages/fetch) primitive is abortable, and is using this api internally. So you are able to create abortable resources with it.
@atk should be able to give you more insight into this.

**Comment by fabiospampinato** [comment]
Yeah signal support is being added to a bunch of APIs, and crucially it can also be used in user code.

**Comment by atk** [comment]
Yes, but unfortunately, AbortController is currently only used in fetch requests and direct event bindings. Obviously, you could use it yourself, but that's hardly more useful than a separate signal.

**Comment by fabiospampinato** [comment]
The usefulness of it comes from being standard, otherwise there would be no usefulness to everything else you could reimplement on your own. Either way feel free to close this issue if you like 👍

**Comment by atk** [comment]
I'm 100% for using standards. I'm just not sure if this should be a separate package or merely an export of createFetch.

**Comment by thetarnav** [comment]
I guess adding it to `fetch` would be a fine starting point.

**Comment by thetarnav** [comment]
@atk You've implemented something like this in the resource package, right?
https://github.com/solidjs-community/solid-primitives/tree/main/packages/resource#makeabortable

**Comment by atk** [comment]
Yes.
