### ISSUE TITLE
@solid-primitives/resource | expose `reason` parameter `abort` callback returned by `makeAbortable`

### ISSUE THREAD

**Issue by vveisard** [solidjs-community/solid-primitives#631]
### Describe The Problem To Be Solved

he `abort` callback returned from `makeAbortable`. does not expose the `reason` parameter for `AbortController.abort()`.

### Suggest A Solution

Expose the `reason` parameter for `AbortController.abort()` in the `abort` callback returned from `makeAbortable`.

**Comment by atk** [comment]
See https://github.com/solidjs-community/solid-primitives/pull/630
