### ISSUE TITLE
createPolled fires twice on load

### ISSUE THREAD

**Issue by apatrida** [solidjs-community/solid-primitives#632]
### Describe the bug

I have a createPolled in a solidjs component, and it calls a server API.  This API is only called from the create polled and nowhere else.  

```
createPolled(
    async () => {
      await checkLiveStreams();
    },
    4 * 60 * 1000
);
```

This fires twice on page load.

If I do a makeTimer (w/interval) for the same, and a makeTimer (w/timeout at 1 second) to do the same basic work, everything happens as expected.

in the attached sample https://stackblitz.com/edit/github-rx3d4k?file=src%2FApp.tsx
you can see the console log "polled item" twice on refresh.

### Minimal Reproduction Link

https://stackblitz.com/edit/github-rx3d4k?file=src%2FApp.tsx

**Comment by thetarnav** [comment]
`createPolled` is meant to be used for derivations (preferably pure) so it shouldn't matter that much.
But it is a bug regardless.
And it's easy to spot why from the source code:
```ts
const [polled, setPolled] = createSignal(untrack(fn.bind(void 0, value))); // <- calls fn
const update = () => setPolled(fn);
createComputed(update); // <- calls fn
```
