### ISSUE TITLE
Unknown file extension /utils/dist/reactivity/index.jsx in solid-presence

### ISSUE THREAD

**Issue by z3phyro** [solidjs-community/solid-primitives#645]
### Describe the bug

When running tests on a component made with Kobalte there is the following error 
<img width="625" alt="image" src="https://github.com/solidjs-community/solid-primitives/assets/15892894/63c3c5c4-2518-44fb-8cb4-f3c86be82f46">

I could find out that it's related with the solid-presence package. The access to the main module is through a js file, but then it references jsx files. I was tinkering with it a bit and when changing the entry point to a jsx files it works for the test but not for the build or npm run dev and viceversa.

I've also noticed similar issue in solid-prevent-scroll package and the router package.

attached an image and the stackblitz example

### Minimal Reproduction Link

https://stackblitz.com/edit/github-xfdh2g-4fkfdg?file=package.json

**Comment by thetarnav** [comment]
How exactly does this relate to solid-primitives? Is there an issue with some of our packages?

**Comment by jer3m01** [comment]
`solid-presence` is a package from https://corvu.dev/docs/utilities/presence/

**Comment by z3phyro** [comment]
My mistake. I'll close this. Open it on corvu github. Thanks for letting me know
