### ISSUE TITLE
createScriptLoader causes rootless resource error

### ISSUE THREAD

**Issue by apatrida** [solidjs-community/solid-primitives#646]
### Describe the bug

In `createScriptLoader` the following code:

```
 setTimeout(() => spread(script, scriptProps, false, true));
```

causes a warning about doing reactive things outside a root not disposing of resources. Changing to:

```
 setTimeout(createCallback(() => spread(script, scriptProps, false, true)));
```

removes the warning.

### Minimal Reproduction Link

not-required

**Comment by atk** [comment]
We specifically added the timeout to move the call of spread out of the context, as otherwise hydration breaks.

**Comment by atk** [comment]
I cannot find createCallback anywhere in the solid-js code. Please re-open once you can provide a working workaround.
