### ISSUE TITLE
Resize-observer ResizeHandler element support generics

### ISSUE THREAD

**Issue by Phinome** [solidjs-community/solid-primitives#647]
### Describe The Problem To Be Solved

in case: 
```tsx
let ref
createResizeObserver(() => ref, ({ width, height }, el) => {
  if (el === ref) console.log(width, height)
});
<div ref={ref}/>
 ```
 `el` is `HTMLElement`, but handler of parameter `el` to `Element`. 

i want to get `offsetWidth` or `offsetHeight` from `el`, but `typescript` would checked failed: "The Element type has no offsetWidth or offsetHeight attribute."

### Suggest A Solution

just like this:
```tsx
export type ResizeHandler<T> = (
  rect: DOMRectReadOnly,
  element: T,
  entry: ResizeObserverEntry,
) => void;
```

**Comment by Phinome** [comment]
no body care？

**Comment by maciek50322** [comment]
In typescript you can always force different type if you are sure it is different type or check it
```tsx
let ref;
createResizeObserver(() => ref, ({ width, height }, el) => {
  // if you are sure of the type
  (el as HTMLElement).offsetWidth;
  // checking if it contains prop you want
  if (offsetWidth in el) el.offsetWidth;
});
<div ref={ref}/>
```
Generics will simplify this for you, but note that typescript also generalize types whenever it can, so if we had generics and
```tsx
let ref: HTMLElement;
let ref2: Element;
createResizeObserver(() => [ref, ref2], ({ width, height }, el) => {
  // `el` would be generalized here to type `Element`, because `HTMLElement` extends `Element`
  // still would have to check it manually
});
<div ref={ref}/>
```

**Comment by Phinome** [comment]
@mackignacio thanks. i take it.
