### ISSUE TITLE
@solid-primitives/storage is not always compatible with SSR

### ISSUE THREAD

**Issue by wadamek65** [solidjs-community/solid-primitives#652]
### Describe The Problem To Be Solved

Simply copy-pasting the examples that are given in the documentation may not work in SolidStart and will throw nasty hydration errors in development that are hard to understand. It may be clear why this happens if someone understands SSR and hydration, it would be nice to add a mention in the documentation somewhere about it.

[Here](https://github.com/wadamek65/treease/blob/main/src/components/TreeProvider/TreeProvider.tsx#L32-L38) is an example of where I stumbled upon it in my own project. The very first example given in the documentation caused me a hydration error.

### Suggest A Solution

Add a mention about using this package in SSR and add a link to [`clientOnly`](https://docs.solidjs.com/solid-start/reference/client/client-only#clientonly) as a potential solution.

I would be willing to create a PR updating the documentation if it sounds okay.

**Comment by atk** [comment]
Thank you for the issue. The error stems from no storage being given in the server and us having no fallback in that case. We should then just return the signal/store as is without persistence.
