### ISSUE TITLE
Please add an example makePersisted using IndexedDB or localforage

### ISSUE THREAD

**Issue by sparecycles** [solidjs-community/solid-primitives#666]
### Describe The Problem To Be Solved

My problem is that very large values fail to be saved via `makePersisted` on `localStorage`, 

The docs mention "there is also `localForage`" but there's no code example and the types don't quite match if you try to use it directly?

<img width="680" alt="image" src="https://github.com/user-attachments/assets/59e20a70-e4cb-4857-82f5-8eec73302b44">

### Suggest A Solution

---

**Comment by sparecycles** [comment]
While it's not too hard to solve, defining the entire AsyncStorage interface did not spark joy.

```ts
const forage = localforage.createInstance({ ... });

const [stuff, setStuff] = makePersisted(createSignal<...>(),
  {
    name: "...",
    storage: {
      getItem(key) {
        return forage.getItem(key);
      },
      key(index) {
        return forage.key(index);
      },
      removeItem(key) {
        return forage.removeItem(key);
      },
      // I don't know why forage's Promise<string> was not compatible with persisted's Promise<void>... 🤷 
      async setItem(key, value) {
        await forage.setItem(key, value);
      },
      clear() {
        return forage.clear();
      },
      // this seems to be a bit of a signature change? (function adapted to property).
      get length() {
        return forage.length();
      },
    },
  },
);
```

**Comment by atk** [comment]
The next major update (soon to be released) will simplify the types. Since we only use getItem, setItem and removeItem, we do not need to constrain the other methods and properties of the storage, so you can put in localforage directly after updating.

**Comment by sparecycles** [comment]
pulled the new release today.  Typescript likes `storage: localforage` now! LGTM!
