### ISSUE TITLE
makePersisted in combination with a store, gives the default value instead of the current value in ui after refresh

### ISSUE THREAD

**Issue by kesteinbakk** [solidjs-community/solid-primitives#699]
### Describe the bug

In this persisted store the default value for theme is "dark":
` const [config, setConfig, init] = makePersisted(createStore(defaultConfig), { name: "config" });`

I use it like this in a solidStart app with Tailwind and themes from DaisyUI:

` <ConfigContext.Provider value={api} >  `
`      <div id="config" data-theme={config.theme}>  `
`         {props.children}  `
`      </div>  `
`  </ConfigContext.Provider>  `
    

This works as expected both for the default value and when users change the theme with a button, triggering a "setConfig" update.

However, after a refresh the default theme is always used by the app, even if logging states that the current theme is something else (see image below).
    
So, the flow is:

- User has not selected a theme - Works as expected with default theme (for instance dark)
- User switches theme (we update the store) - Works as expected (for instance setting theme to light, and ui changes to light)
- User refresh page - Expecting the light theme to be preserved. UI shows dark theme, but a console log from a createEffect shows light theme (as selected by user). State is correct, but UI is not in accordance with state. 
- If I store the current config.theme in a signal. Letting the user trigger an action which changes the theme, and then instantly afterwards changing it back to the value from the signal, the app will display the correct theme (as stored in the store and now the signal).

**However,** when trying to recreate this at https://stackblitz.com/ the same code runs as expected, with the correct theme being in effect in the ui also after a refresh. 

So, I guess this must have something to do with SolidStart and maybe SSR. Feel free to close the issue if it's not relevant.

Code in local dev on a SolidStart project:
![image](https://github.com/user-attachments/assets/e59827fc-caa6-4ead-89f5-3d10db26aa84)

Same code with same clicks in Stackblitz:
![image](https://github.com/user-attachments/assets/587a0bc3-3964-46e4-8b00-a0dac3c5c03f)

### Minimal Reproduction Link

https://stackblitz.com/edit/github-zwpkd3?file=src%2Ficons%2FMyIcons.tsx

**Comment by atk** [comment]
There is no localStorage in the server and makePersisted just returns the signal/store if no storage API is provided, so the server version cannot persist the style. If you want to make sure to persist the theme in a way that is available on the server, please use cookieStorage from the same package; If you are using stackblitz, it *might* be neccessary to provide getRequestHeaders and getResponseHeaders to its options: https://github.com/solidjs-community/solid-primitives/tree/main/packages/storage#cookiestorage
