### ISSUE TITLE
How to make the JSON file for i18n?

### ISSUE THREAD

**Issue by huazhenhz** [solidjs-community/solid-primitives#719]
I don't understand how to use the i18n dictionary JSON files yet...
Are ther any examples or detailed documentation?
Thanks a lot!

**Comment by huazhenhz** [comment]
The relevant documentation is difficult to understand...

**Comment by huazhenhz** [comment]
Maybe the example can refer to Svelte as below:
https://svelte.dev/playground/de39de663ef2445b8fe17b79c500013b?version=5.2.1

**Comment by huazhenhz** [comment]
I think the Svelte documentation is much clearer...

**Comment by 0-don** [comment]
https://github.com/0-don/coding.global-web here is an example if you are still looking @huazhenhz
