### ISSUE TITLE
[RAF] allow limiting fps when > 60

### ISSUE THREAD

**Issue by titoBouzout** [solidjs-community/solid-primitives#74]
https://github.com/davedbase/solid-primitives/tree/43d9abed17cd61cda4238957db82eabafe0ea5e9/packages/raf

Currently, the RAF package provides a way to run animations slower than 60 fps. When animations are faster than 60fps then it just uses the screen refresh rate and doesn't limit the execution. See https://github.com/davedbase/solid-primitives/blob/43d9abed17cd61cda4238957db82eabafe0ea5e9/packages/raf/src/index.ts#L38-L42

It would be nice to allow limit the fps also when faster than 60fps because allows saving resources like cpu, battery, etc. For some animation/computations, a lower fps could be considered enough by the developers. In an example, your screen refresh rate is 300, but you consider that 60 or 120 is more than enough for the computations at hand.

I would like to add this some day, so is more like a note to self than a request, but feel free to take over if you feel like.

**Comment by davedbase** [comment]
If you have time and want to submit a PR, I'd certainly consider it.

**Comment by thetarnav** [comment]
Could leave this one up, until it's actually resolved.

**Comment by titoBouzout** [comment]
> Could leave this one up, until it's actually resolved.

That was the idea xD

**Comment by davedbase** [comment]
Oops sorry, trigger happy :-p lol
