### ISSUE TITLE
package proposition: Range

### ISSUE THREAD

**Issue by thetarnav** [solidjs-community/solid-primitives#80]
If we decided to do a API preview/discussion before the implementation, then here we go :)

I'm proposing adding a new Control Flow package, that would be adding a nicer and more optimised way of repeating a JSX element n-times. For example when wanting to display:
- some kind of count with individual elements – _number of stars by rendering each one as a star icon? 😅_
- numbers from x to y
- ?

#### Optimisation opportunities: (compared to using `<Index>` for it)
- no array of empty items need to be created
- there is no array, so there are no array items, so no signals for those items need to be created and kept in memory
- cleaner interface

#### The `mapRange` primitive – powering `<Range>` component:
Usage:
```ts
const [length, setLength] = createSignal(10)
const mapped = mapRange(length, index => {
   const [value, setValue] = createSignal(index);
   createEffect(() => {...})
   return value
})
```
Definition:
```ts
function mapRange<T>(
  length: Accessor<number>,
  mapFn: (i: number) => T,
  options?: { fallback?: Accessor<T> }
): Accessor<T[]>;
```

#### The `<Range>` component:
Usage:
```tsx
<Range of={10}>
   <div></div>
</Range>

with a render prop:
<Range of={10}>
   {n => <div>{n}</div>}
</Range>

with fallback:
<Range of={0} fallback={<p>no items...</p>}>
   <div></div>
</Range>
```
Comparing to how it currently can be achieved:
```tsx
<Index each={new Array(10)}>
   {(_, n) => <div>{n}</div>}
</Index>
```
Definition:
```ts
function Range<T>(props: {
  of: number;
  fallback?: T;
  children: (index: number) => T;
}): Accessor<T[]>;
```

#### More props?

I think that a single `of` prop is enough for most usage cases, and any range can still be achieved:
```tsx
{/* from 5 to 15 */}
<Range of={10}>
   {n => <div>{n + 5}</div>}
</Range>
```
But a few additional props could possibly be helpful:
- `from` - start of the range (0 by default)
- `to` - end of the range *(an alternative to `of` as it also dictates the range size)*
- `by` - increment numbers by n (1 by default)

The downside of adding those could be:
- increased complexity of the component
- wasteful re-rendering of all of the elements in some cases *(e.g. changing the increment_by value)*

Thoughts? :)

**Comment by titoBouzout** [comment]
Neat! I have found myself having to do this a couple of times. A range package would be welcome. 

The only suggestion I would have is to align it to Python Range in case the additional props get considered, as it is going to be more intuitive to use for people that are familiar with it.  There's also https://github.com/tc39/proposal-Number.range , 

```jsx
<Range stop={10}>
   {n => <div>{n}</div>}
</Range>

<Range start={1} stop={10} step={2}>
   {n => <div>{n}</div>}
</Range>

// vs

<Range from={1} to={10} by={2}>
   {n => <div>{n}</div>}
</Range>
```

**Comment by titoBouzout** [comment]
Maybe the package you originally intent to create could be called `Repeat`, that won't cause confusion with what some people may expect from `Range` and would avoid the extra complexity.

**Comment by thetarnav** [comment]
Nice, I didn't know about the tc39 proposal.
As for the suggestions, I don't really agree with the first one: I don't feel like we should stay idiomatic with any language that isn't JS/TS/SolidJS.
Range **from** x **to** y **by** z, reads a little better then Range **start**ing at x **stop**ping at y **step**ping by z. But on the other hand **step** is more clear about it's purpose than **by**.

With the second suggestion I kinda agree, because those will probably end up being two (or even three) separate components, and mapping primitives. Just because the implementations are not compatible with each other.
But if renaming the component or not will probably depend on if the additional primitives will be made – personally I'm fine with having just a `<Range of={x}>`, don't need more then that. Although a name like `<Repeat times={x}>` would still work. Would the entire package be named `repeat` if the rest of the components won't be shipped? And then renamed if they'll be added in the future...

**Comment by titoBouzout** [comment]
I agree, staying idiomatic to the context is the best, but the concept of range seems to be somewhat settled. The comparison table shows some consistency between the various languages on the syntax, which just makes it easy to understand, use and remember.  https://github.com/tc39/proposal-Number.range/blob/master/compare.md#comparison

If the package doesnt hope to include the other options, then `Repeat` sounds better to me, although a `<Range to={5}>` with pending implementation of the other functionalities doesn't sound bad and leaves the door open for improvements. Well, thats just my opinion.

**Comment by atk** [comment]
Maybe we could also implement a shorthand `<Range {...[start, to, step?]}>`.

**Comment by thetarnav** [comment]
@atk What would be there to implement for it? Props `start`, `to` and `step` would have to allow accessors?

**Comment by atk** [comment]
I just meant props.0/1/2 as aliases.

**Comment by thetarnav** [comment]
So something like this? https://playground.solidjs.com/?hash=509101997&version=1.3.13
Seams pretty nice!

**Comment by thetarnav** [comment]
Okay, so if we go with shipping only the `<Repeat>` component, the package name could be `repeat`, with such API:
```ts
function repeat<T>(
  times: Accessor<number>,
  mapFn: (i: number) => T,
  options?: { fallback?: Accessor<T> }
): Accessor<T[]>;

function Repeat<T>(props: {
  times: number;
  fallback?: T;
  children: (index: number) => T;
}): Accessor<T[]>;
```
And that's it

But if we want the rest of the functionality of `<Range>` the API could be:
```ts
declare function repeat<T>(
  times: Accessor<number>,
  mapFn: (i: number) => T,
  options?: { fallback?: Accessor<T> }
): Accessor<T[]>;

declare function Repeat<T>(props: {
  times: number;
  fallback?: T;
  children: ((index: number) => T) | T;
}): Accessor<T[]>;

// always maps new elements for added numbers
declare function mapRange<T>(
  start: Accessor<number>,
  to: Accessor<number>,
  step: Accessor<number>,
  mapFn: (i: number) => T,
  options?: { fallback?: Accessor<T> }
): Accessor<T[]>;

// (will also allow for the shorthand [start, to, step?])
declare function Range<T>(props: {
  start?: number;
  to: number;
  step?: number;
  fallback?: T;
  children: ((index: number) => T) | T;
}): Accessor<T[]>;

// reuses mapped elements, changes only the signal number value
declare function indexRange<T>(
  start: Accessor<number>,
  to: Accessor<number>,
  step: Accessor<number>,
  mapFn: (i: Accessor<number>) => T,
  options?: { fallback?: Accessor<T> }
): Accessor<T[]>;

// (will also allow for the shorthand [start, to, step?])
declare function IndexRange<T>(props: {
  start?: number;
  to: number;
  step?: number;
  fallback?: T;
  children: ((index: Accessor<number>) => T) | T;
}): Accessor<T[]>;

```
