### ISSUE TITLE
built-in node fetch?

### ISSUE THREAD

**Issue by tomByrer** [solidjs-community/solid-primitives#88]
Node v17.5 added built-in `fetch()`, still needs flag.
But what to do when Node v18 releases?
https://github.com/solidjs-community/solid-primitives/blob/main/packages/fetch/src/server.ts

**Comment by atk** [comment]
That's a good point. We should make it an optional dependency that's only required when no native implementation is present. I'll see to it later.

**Comment by atk** [comment]
Should be solved by https://github.com/solidjs-community/solid-primitives/pull/89 once merged.

**Comment by thetarnav** [comment]
`@solid-primitives/fetch@1.1.0` should be using `fetch` if available.
