### ISSUE TITLE
requrest to lower throttle, debounce to stage 1

### ISSUE THREAD

**Issue by trusktr** [solidjs-community/solid-primitives#93]
And for any similar APIs, the same.

They have different shape APIs, but they should be the same for consistency. I think they should be stage 1, based on the [proposed staging process](https://github.com/solidjs-community/solid-primitives/discussions/92).

If we move too fast, we're going to end with inconsistent APIs like throttle and debounce currently are, or maybe the wrong APIs.

We need a way to publish pre-stage-3 packages with clear labeling that indicates consensus isn't reached on the API shape or features yet. Maybe we do it with certain addition to the package name, or use only `0.0.0-*` pre-release versioning, or something.

**Comment by trusktr** [comment]
As an example, if someone knows how to use `createThrottle`, then they'll import `createDebounce` thinking to do roughly the same, but they'll get it wrong by intuition because the shape is unexpected.

**Comment by trusktr** [comment]
PR: https://github.com/solidjs-community/solid-primitives/pull/94

Not sure I did it right.

Also any other APIs that need consistency?

**Comment by thetarnav** [comment]
All the versions lower than 1.0.0 could work for pre-stage-3. This is what we've been doing up to this point, just very very inconsistently.

**Comment by thetarnav** [comment]
Btw there is a plan to move both of these under a one package. `schedule` I believe. So that could be a good opportunity to unify the api.
